import type { AnimationDoc } from "./types";

const an = (slug: string) => `registry/animations/${slug}.tsx`;

const KF = {
  shimmer: `@keyframes shimmer {\n  from { background-position: 200% center; }\n  to { background-position: -200% center; }\n}`,
  blurIn: `@keyframes blur-in {\n  from { opacity: 0; filter: blur(10px); transform: translateY(6px); }\n  to { opacity: 1; filter: blur(0); transform: translateY(0); }\n}`,
  slideIn: `@keyframes slide-in {\n  from { opacity: 0; transform: translateX(-14px); }\n  to { opacity: 1; transform: translateX(0); }\n}`,
  beam: `@property --beam-angle {\n  syntax: "<angle>";\n  inherits: false;\n  initial-value: 0deg;\n}\n@keyframes beam { to { --beam-angle: 360deg; } }`,
  shine: `@keyframes shine {\n  0% { transform: translateX(-120%) skewX(-15deg); }\n  60%, 100% { transform: translateX(220%) skewX(-15deg); }\n}`,
  orbit: `@keyframes orbit {\n  from { transform: rotate(0deg) translateX(var(--orbit-r, 44px)) rotate(0deg); }\n  to { transform: rotate(360deg) translateX(var(--orbit-r, 44px)) rotate(-360deg); }\n}`,
  bounce: `@keyframes bounce-dot {\n  0%, 80%, 100% { transform: translateY(0); opacity: 0.4; }\n  40% { transform: translateY(-6px); opacity: 1; }\n}`,
  marquee: `@keyframes marquee {\n  from { transform: translateX(-50%); }\n  to { transform: translateX(0); }\n}`,
  pulse: `@keyframes pulse-soft {\n  0%, 100% { opacity: 0.55; }\n  50% { opacity: 1; }\n}`,
  wordIn: `@keyframes word-in {\n  from { opacity: 0; transform: translateY(0.6em); filter: blur(4px); }\n  to { opacity: 1; transform: translateY(0); filter: blur(0); }\n}`,
  ripple: `@keyframes ripple {\n  from { transform: translate(-50%, -50%) scale(0); opacity: 0.35; }\n  to { transform: translate(-50%, -50%) scale(4); opacity: 0; }\n}`,
  check: `@keyframes pop {\n  0% { transform: scale(0.6); opacity: 0; }\n  60% { transform: scale(1.08); opacity: 1; }\n  100% { transform: scale(1); }\n}\n@keyframes draw { to { stroke-dashoffset: 0; } }\n@keyframes word-in {\n  from { opacity: 0; transform: translateY(0.6em); filter: blur(4px); }\n  to { opacity: 1; transform: translateY(0); filter: blur(0); }\n}`,
  meteor: `@keyframes meteor {\n  0% { transform: rotate(215deg) translateX(0); opacity: 1; }\n  70% { opacity: 1; }\n  100% { transform: rotate(215deg) translateX(-420px); opacity: 0; }\n}`,
  tileIn: `@keyframes tile-in {\n  from { opacity: 0; transform: scale(0.7); }\n  to { opacity: 1; transform: scale(1); }\n}`,
  wipeIn: `@keyframes wipe-in {\n  from { clip-path: inset(0 0 0 100%); transform: translateY(0.35em); opacity: 0; }\n  to { clip-path: inset(0 0 0 0); transform: translateY(0); opacity: 1; }\n}`,
  gradientPan: `@keyframes gradient-pan {\n  from { background-position: 0% 50%; }\n  to { background-position: 150% 50%; }\n}`,
  beamTravel: `@keyframes beam-travel {\n  from { stroke-dashoffset: 28; }\n  to { stroke-dashoffset: -100; }\n}`,
  confetti: `@keyframes confetti {\n  0% { transform: translate(-50%, 0) rotate(0deg); opacity: 1; }\n  60% { transform: translate(calc(-50% + var(--cx)), var(--cy)) rotate(calc(var(--cr) * 0.6)); opacity: 1; }\n  100% { transform: translate(calc(-50% + var(--cx) * 1.3), 40px) rotate(var(--cr)); opacity: 0; }\n}`,
  sparkle: `@keyframes sparkle {\n  0%, 100% { opacity: 0; transform: scale(0) rotate(0deg); }\n  50% { opacity: 1; transform: scale(1) rotate(90deg); }\n}`,
  pulseRing: `@keyframes pulse-ring {\n  0% { transform: scale(1); opacity: 0.6; }\n  100% { transform: scale(1.4); opacity: 0; }\n}`,
  particleBurst: `@keyframes particle-burst {\n  from { opacity: 1; transform: translate(0, 0) scale(1); }\n  to { opacity: 0; transform: translate(var(--burst-x), var(--burst-y)) scale(0.35); }\n}`,
  radialOrbit: `@keyframes radial-orbit {\n  from { transform: rotate(var(--start-angle, 0deg)); }\n  to { transform: rotate(calc(var(--start-angle, 0deg) + 360deg)); }\n}\n@keyframes radial-counter {\n  from { transform: translate(-50%, calc(-50% - var(--orbit-r, 80px))) rotate(calc(var(--start-angle, 0deg) * -1)); }\n  to { transform: translate(-50%, calc(-50% - var(--orbit-r, 80px))) rotate(calc(var(--start-angle, 0deg) * -1 - 360deg)); }\n}`,
  digitPop: `@keyframes digit-pop {\n  from { opacity: 0; filter: blur(2px); transform: translate(calc(var(--pop-x, 0) * 8px), calc(var(--pop-y, 1) * 8px)); }\n  to { opacity: 1; filter: blur(0); transform: translate(0, 0); }\n}`,
  badge: `@keyframes badge-slide {\n  from { transform: translate(var(--bx, -8px), 12px); }\n  to { transform: translate(0, 0); }\n}\n@keyframes bell-ring {\n  0%, 100% { transform: rotate(0); }\n  15% { transform: rotate(14deg); }\n  30% { transform: rotate(-10deg); }\n  45% { transform: rotate(6deg); }\n  60% { transform: rotate(-3deg); }\n  75% { transform: rotate(1deg); }\n}`,
  errorShake: `@keyframes error-shake {\n  0% { transform: translateX(0); animation-timing-function: cubic-bezier(0.36, 0.07, 0.19, 0.97); }\n  20% { transform: translateX(8px); animation-timing-function: cubic-bezier(0.36, 0.07, 0.19, 0.97); }\n  40% { transform: translateX(-7px); animation-timing-function: cubic-bezier(0.36, 0.07, 0.19, 0.97); }\n  60% { transform: translateX(5px); animation-timing-function: cubic-bezier(0.36, 0.07, 0.19, 0.97); }\n  80% { transform: translateX(-3px); animation-timing-function: cubic-bezier(0.36, 0.07, 0.19, 0.97); }\n  100% { transform: translateX(0); }\n}`,
  clear: `@keyframes word-dissolve {\n  0% { opacity: 1; transform: translateY(0); filter: blur(0); text-shadow: 0 0 0 transparent; }\n  30% { text-shadow: 0 0 10px currentColor; }\n  100% { opacity: 0; transform: translateY(12px); filter: blur(2px); text-shadow: 0 0 0 transparent; }\n}\n@keyframes placeholder-drop {\n  from { opacity: 0; transform: translateY(-10px); filter: blur(2px); }\n  to { opacity: 1; transform: translateY(0); filter: blur(0); }\n}`,
  like: `@keyframes like-pop {\n  0% { transform: scale(1); }\n  30% { transform: scale(0.8); }\n  65% { transform: scale(1.25); }\n  100% { transform: scale(1); }\n}\n@keyframes like-burst {\n  0% { opacity: 0; transform: translate(0, 0) scale(0.4); }\n  20% { opacity: 1; transform: translate(calc(var(--px) * 0.25), calc(var(--py) * 0.25)) scale(1); }\n  100% { opacity: 0; transform: translate(var(--px), var(--py)) scale(0.5); }\n}\n@keyframes digit-pop {\n  from { opacity: 0; filter: blur(2px); transform: translate(calc(var(--pop-x, 0) * 8px), calc(var(--pop-y, 1) * 8px)); }\n  to { opacity: 1; filter: blur(0); transform: translate(0, 0); }\n}`,
  swap: `@keyframes swap-out {\n  to { opacity: 0; filter: blur(2px); transform: translateY(calc(var(--swap-y, 4px) * -1)); }\n}\n@keyframes swap-in {\n  from { opacity: 0; filter: blur(2px); transform: translateY(var(--swap-y, 4px)); }\n}`,
  think: `@keyframes shimmer {\n  from { background-position: 200% center; }\n  to { background-position: -200% center; }\n}\n@keyframes swap-out {\n  to { opacity: 0; filter: blur(2px); transform: translateY(calc(var(--swap-y, 4px) * -1)); }\n}\n@keyframes swap-in {\n  from { opacity: 0; filter: blur(2px); transform: translateY(var(--swap-y, 4px)); }\n}`,
  bannerIn: `@keyframes banner-in {\n  from { opacity: 0; filter: blur(2px); transform: translateY(16px) scale(0.96); }\n}`,
  matrix: `@keyframes matrix-pulse {\n  0%, 45%, 100% { background-color: color-mix(in oklab, var(--foreground) 25%, transparent); }\n  15% { background-color: var(--foreground); }\n}`,
};

export const animations: AnimationDoc[] = [
  {
    slug: "text-shimmer", name: "متن درخشان", file: an("text-shimmer"), css: KF.shimmer,
    desc: "نوری که از روی متن می‌گذره، مناسب حالت «در حال فکر کردن».",
    usage: `import { TextShimmer } from "@/components/animations/text-shimmer"\n\n<TextShimmer className="text-lg font-semibold">در حال فکر کردن…</TextShimmer>`,
    props: [{ name: "duration", type: "number", default: "3", desc: "ثانیه برای هر دور." }],
    promptBullets: ["Horizontal gradient from muted-foreground to foreground with background-clip:text and moving background-position.", "Text must stay selectable and readable; only the color animates."],
  },
  {
    slug: "typewriter", name: "تایپ‌شونده", file: an("typewriter"), css: KF.pulse,
    desc: "متنی که حرف‌به‌حرف ظاهر میشه و اتصال حروف فارسی را درست نگه می‌داره.",
    usage: `import { Typewriter } from "@/components/animations/typewriter"\n\n<Typewriter text="یک فرم ثبت‌نام فارسی بساز." speed={70} loopDelay={2000} />`,
    props: [
      { name: "speed", type: "number", default: "70", desc: "میلی‌ثانیه برای هر حرف." },
      { name: "loopDelay", type: "number", default: "0", desc: "مکث در پایان و شروع دوباره. صفر یعنی فقط یک بار." },
    ],
    notes: ["چون هر بار زیررشته‌ی کامل رندر میشه، حروف فارسی درست به هم می‌چسبن. حرف‌ها را جدا انیمیت نکنید."],
    promptBullets: ["Render text.slice(0, n), not separate letters, so Persian glyph joining stays intact.", "Cursor is a pulsing vertical bar after the text; aria-label is the full string."],
  },
  {
    slug: "counter", name: "شمارنده", file: an("counter"), wide: true,
    desc: "عددی که وقتی وارد دید شد، با اعداد فارسی تا مقدار نهایی بالا میره.",
    usage: `import { Counter } from "@/components/animations/counter"\n\n<Counter to={12_450_000} unit="تومان" className="text-3xl font-bold" />`,
    props: [
      { name: "to / from", type: "number", desc: "مقصد و شروع." },
      { name: "duration", type: "number", default: "1600", desc: "میلی‌ثانیه." },
      { name: "format", type: "(n) => string", default: "faNumber", desc: "قالب خودِ عدد." },
      { name: "unit", type: "ReactNode", desc: "واحد، بیرون از جعبه‌ی عدد تا هیچ‌وقت جابه‌جا نشود." },
    ],
    notes: ["مقدار نهایی به شکل نامرئی زیر عدد رندر میشه تا عرض از اول رزرو بشه. واحد هم بیرون از آن جعبه‌ست، پس وقتی تعداد رقم‌ها عوض میشه (مثلاً عبور از ۱۰ میلیون) نه عدد می‌پره نه «تومان»."],
    promptBullets: ["Start with IntersectionObserver when it enters view; ease-out cubic easing.", "requestAnimationFrame with cleanup on unmount.", "Reserve width with an invisible copy of the final value, overlay the animated number absolute and RTL (anchor on the ones digit), and render the unit outside that box so digit-count changes do not jiggle."],
  },
  {
    slug: "blur-text", name: "ظهور تار", file: an("blur-text"), css: KF.blurIn,
    desc: "کلمه‌هایی که از راست به چپ، از تاری بیرون می‌آن.",
    usage: `import { BlurText } from "@/components/animations/blur-text"\n\n<h1 className="text-4xl font-bold"><BlurText text="کامپوننت‌هایی که فارسی را می‌فهمند" /></h1>`,
    props: [{ name: "delay", type: "number", default: "120", desc: "فاصله‌ی شروع هر کلمه (میلی‌ثانیه)." }],
    promptBullets: ["Each word is an inline-block span with an increasing animation-delay; keep gaps with &nbsp;.", "Because the document is rtl, natural word order is already right-to-left; do not reverse it."],
  },
  {
    slug: "animated-tabs", name: "تب‌های لغزان", file: an("animated-tabs"),
    desc: "تب‌هایی که نشانگر زیرشون به‌نرمی به تب فعال سُر می‌خوره.",
    usage: `import { AnimatedTabs } from "@/components/animations/animated-tabs"\n\n<AnimatedTabs items={["همه", "فعال", "بایگانی"]} onChange={setTab} />`,
    props: [{ name: "items", type: "string[]", desc: "برچسب تب‌ها." }, { name: "value / onChange", type: "number", desc: "شاخص تب فعال." }],
    promptBullets: ["Indicator uses inset-inline-start with a transition on that property; width calc((100% - padding) / n).", "No getBoundingClientRect measurement."],
  },
  {
    slug: "border-beam", name: "حاشیه‌ی نورانی", file: an("border-beam"), css: KF.beam,
    desc: "پرتو نوری که دور کارت می‌چرخه.",
    usage: `import { BorderBeam } from "@/components/animations/border-beam"\n\n<BorderBeam><div className="p-4">پلن حرفه‌ای</div></BorderBeam>`,
    props: [{ name: "duration", type: "number", default: "4", desc: "ثانیه برای یک دور." }, { name: "color", type: "string", default: "var(--foreground)", desc: "رنگ پرتو." }],
    promptBullets: ["conic-gradient with a --beam-angle variable registered via @property so it can animate.", "Gradient layer inset-[-100%] behind the card with 1px padding so only the border shows."]
  },
  {
    slug: "shine-button", name: "دکمه‌ی درخشان", file: an("shine-button"), css: KF.shine, registryDeps: ["button"],
    desc: "نوار نوری که از روی دکمه می‌گذره، برای عمل اصلی صفحه.",
    usage: `import { ShineButton } from "@/components/animations/shine-button"\n\n<ShineButton><Sparkles />ارتقا به پرو</ShineButton>`,
    promptBullets: ["An absolute span with a skewed gradient that sweeps right-to-left every 2s; pointer-events-none.", "Use on the page's primary button only, one instance."],
  },
  {
    slug: "dock", name: "داک", file: an("dock"), wide: true,
    desc: "آیکون‌هایی که با نزدیک شدن ماوس بزرگ میشن.",
    usage: `import { Dock } from "@/components/animations/dock"\n\n<Dock items={[{ icon: Home, label: "خانه" }, { icon: Search, label: "جست‌وجو" }]} />`,
    props: [{ name: "items", type: "{ icon; label; onClick? }[]", desc: "آیکون‌ها با برچسب برای aria." }],
    promptBullets: ["CSS only: hover:scale-[1.4] on the item; container h-20 with items-end so the grown icon stays in frame, neighbors scale a bit via :has(+ :hover) and :hover + &.", "origin-bottom so they grow from the bottom; role=toolbar."],
  },
  {
    slug: "animated-list", name: "فهرست متحرک", file: an("animated-list"), css: KF.slideIn,
    desc: "آیتم‌هایی که یکی‌یکی از راست وارد میشن، مناسب اعلان‌ها.",
    usage: `import { AnimatedList } from "@/components/animations/animated-list"\n\n<AnimatedList stagger={200}>\n  <NotificationRow … />\n  <NotificationRow … />\n</AnimatedList>`,
    props: [{ name: "stagger", type: "number", default: "200", desc: "فاصله‌ی ورود آیتم‌ها (میلی‌ثانیه)." }],
    promptBullets: ["Each child in an li with animation-delay = index × stagger; enter from the right (negative translateX).", "animation-fill-mode: both so they stay hidden until their turn."],
  },
  {
    slug: "orbit", name: "مدار", file: an("orbit"), css: KF.orbit,
    desc: "عناصری که دور یک مرکز می‌چرخن و همیشه رو به بالا می‌مونن.",
    usage: `import { Orbit } from "@/components/animations/orbit"\n\n<Orbit center={<Logo />} items={[{ node: <Icon />, radius: 64, duration: 9 }, { node: <Icon />, radius: 44, duration: 6 }]} />`,
    props: [{ name: "items", type: "{ node; radius; duration?; delay? }[]", desc: "هر آیتم مدار خودش را داره." }, { name: "size", type: "number", default: "160", desc: "قطر ظرف." }],
    promptBullets: ["Keyframe: rotate(a) translateX(r) rotate(-a) so the item does not spin; radius via --orbit-r.", "Dashed rings for each unique radius."],
  },
  {
    slug: "tilt-card", name: "کارت سه‌بعدی", file: an("tilt-card"),
    desc: "کارتی که با حرکت ماوس کج میشه.",
    usage: `import { TiltCard } from "@/components/animations/tilt-card"\n\n<TiltCard className="p-4">…</TiltCard>`,
    props: [{ name: "max", type: "number", default: "14", desc: "حداکثر زاویه به درجه." }],
    promptBullets: ["perspective(600px) rotateX/rotateY from relative mouse position (−0.5 to 0.5); reset to zero on mouseleave.", "Short 150ms transition so motion is smooth but responsive."],
  },
  {
    slug: "loading-dots", name: "نقاط بارگذاری", file: an("loading-dots"), css: KF.bounce,
    desc: "سه نقطه‌ی ضربان‌دار برای انتظارهای کوتاه.",
    usage: `import { LoadingDots } from "@/components/animations/loading-dots"\n\n<LoadingDots label="در حال دریافت پاسخ" />`,
    promptBullets: ["Three dots with animation-delay 0, 160, and 320ms; role=status and a text label beside them."],
  },
  {
    slug: "marquee", name: "نوار متحرک", file: an("marquee"), css: KF.marquee,
    desc: "نوار متحرک با حرکت پیوسته از چپ به راست، در جهت طبیعی فارسی.",
    usage: `import { Marquee } from "@/components/animations/marquee"\n\n<Marquee duration={20}>\n  {tags.map((t) => <Badge key={t}>{t}</Badge>)}\n</Marquee>`,
    props: [{ name: "duration", type: "number", default: "30", desc: "ثانیه برای یک دور." }, { name: "gap", type: "string", default: '"1rem"', desc: "فاصله‌ی آیتم‌ها." }],
    promptBullets: ["Render the content twice and animate the container from translateX(-50%) to 0 for a seamless left-to-right loop.", "Outer container dir=ltr for transform math, inner content dir=rtl; fade both edges with mask-image."],
  },
  {
    slug: "reveal", name: "ظهور هنگام اسکرول", file: an("reveal"),
    desc: "بخش‌هایی که وقتی وارد دید میشن بالا می‌آن، فقط یک بار.",
    usage: `import { Reveal } from "@/components/animations/reveal"\n\n<Reveal delay={100}><FeatureCard /></Reveal>`,
    props: [{ name: "delay", type: "number", default: "0", desc: "تأخیر شروع (میلی‌ثانیه)." }],
    promptBullets: ["IntersectionObserver with a negative bottom rootMargin so it starts a bit late; disconnect after first entry.", "Transition opacity and transform; if IntersectionObserver is missing, show immediately."],
  },
  {
    slug: "word-rotate", name: "چرخش کلمه", file: an("word-rotate"), css: KF.wordIn,
    desc: "یک جای جمله که بین چند کلمه می‌چرخه و هر کلمه با تاری نرم بالا می‌آد.",
    usage: `import { WordRotate } from "@/components/animations/word-rotate"\n\n<h1>کامپوننت‌های فارسی، برای <WordRotate words={["توسعه‌دهنده", "طراح", "وایب‌کدر"]} /></h1>`,
    props: [{ name: "words", type: "string[]", desc: "کلمه‌ها به ترتیب." }, { name: "interval", type: "number", default: "2200", desc: "میلی‌ثانیه برای هر کلمه." }],
    promptBullets: ["inline-grid container with an invisible copy of the longest word so width stays fixed and the sentence does not jump.", "Render the new word with a fresh key so the CSS animation restarts; aria-live=polite."],
  },
  {
    slug: "text-scramble", name: "رمزگشایی متن", file: an("text-scramble"),
    desc: "حرف‌هایی که بین حروف تصادفی فارسی می‌چرخن و از ابتدای جمله یکی‌یکی ثابت میشن.",
    usage: `import { TextScramble } from "@/components/animations/text-scramble"\n\n<TextScramble text="کامپوننت‌هایی که فارسی را می‌فهمند" className="text-xl font-bold" />`,
    props: [{ name: "speed", type: "number", default: "40", desc: "میلی‌ثانیه برای هر فریم." }],
    promptBullets: ["Letter pool is Persian letters only (not Latin) so the word shape stays Persian; spaces and ZWNJ stay untouched.", "Resolve from the start of the string (the right in RTL); full text in aria-label."],
  },
  {
    slug: "odometer", name: "شماره‌انداز", file: an("odometer"), wide: true,
    desc: "هر رقم مثل کنتور مکانیکی به مقدار جدید می‌غلته، مناسب قیمت‌های زنده.",
    usage: `import { Odometer } from "@/components/animations/odometer"\n\n<Odometer value={price} unit="تومان" className="text-3xl font-bold" />`,
    props: [{ name: "value", type: "number", desc: "مقدار. با هر تغییر، رقم‌ها می‌غلتن." }, { name: "unit", type: "string", desc: "واحد کوچک کنار عدد." }],
    promptBullets: ["Each digit is a 1em-tall overflow-hidden column with a 0–9 strip inside, moved by translateY(-n em).", "Digits inside the number are dir=ltr; thousands separator «٬» is static; ~700ms transition."],
  },
  {
    slug: "ripple-button", name: "دکمه‌ی موجی", file: an("ripple-button"), css: KF.ripple, registryDeps: ["button"],
    desc: "موجی که از نقطه‌ی لمس بیرون می‌زنه، برای بازخورد لمسی در موبایل.",
    usage: `import { RippleButton } from "@/components/animations/ripple-button"\n\n<RippleButton>پرداخت</RippleButton>`,
    promptBullets: ["On click, take relative click coords and add a round span there with a scale animation; remove it after 650ms.", "Button overflow-hidden; text z-index above the ripple."],
  },
  {
    slug: "magnetic-button", name: "دکمه‌ی آهنربایی", file: an("magnetic-button"), registryDeps: ["button"],
    desc: "دکمه‌ای که وقتی ماوس نزدیک میشه، کمی به سمتش کشیده میشه.",
    usage: `import { MagneticButton } from "@/components/animations/magnetic-button"\n\n<MagneticButton strength={10}>شروع کنید</MagneticButton>`,
    props: [{ name: "strength", type: "number", default: "10", desc: "حداکثر جابه‌جایی به پیکسل." }],
    promptBullets: ["Hit area larger than the button (padding) so reaction starts before the pointer arrives; reset to zero on mouseleave.", "Short ease-out transition; inert on touch and that is fine."],
  },
  {
    slug: "progress-ring", name: "حلقه‌ی پیشرفت", file: an("progress-ring"),
    desc: "حلقه‌ی SVG که با ورود به دید پر میشه و درصد فارسی وسطش می‌نشینه.",
    usage: `import { ProgressRing } from "@/components/animations/progress-ring"\n\n<ProgressRing value={72} label="هدف ماهانه" />`,
    props: [{ name: "value", type: "number", desc: "درصد ۰ تا ۱۰۰." }, { name: "size / stroke", type: "number", default: "96 / 8", desc: "قطر و ضخامت." }],
    promptBullets: ["Two SVG circles; the second has stroke-dasharray equal to circumference and stroke-dashoffset mapped to percent, with a transition.", "svg with -rotate-90 so it starts at the top; role=progressbar and percent with Persian «٪»."],
  },
  {
    slug: "success-check", name: "تیک موفقیت", file: an("success-check"), css: KF.check,
    desc: "دایره‌ای که جهش می‌کنه و تیکش را خودش می‌کشه، برای پایان پرداخت و ثبت‌نام.",
    usage: `import { SuccessCheck } from "@/components/animations/success-check"\n\n<SuccessCheck label="پرداخت انجام شد" />`,
    promptBullets: ["Check path with stroke-dasharray equal to its length and stroke-dashoffset from that value to zero (draw-on).", "Circle pops with a little overshoot; label appears after the check with a delay."],
  },
  {
    slug: "meteors", name: "بارش شهاب", file: an("meteors"), css: KF.meteor,
    desc: "رگه‌های نوری که از بالا-راست به پایین-چپ می‌ریزن، برای هیرو و کارت‌های ویژه.",
    usage: `import { Meteors } from "@/components/animations/meteors"\n\n<div className="relative overflow-hidden rounded-xl border p-8">\n  <Meteors count={12} />\n  …\n</div>`,
    props: [{ name: "count", type: "number", default: "12", desc: "تعداد شهاب." }],
    promptBullets: ["Each meteor is a 1px gradient line with a bright head; rotate(215deg) and negative translateX so they fall right to left.", "Delay and duration are pseudo-random from the index so they stay stable across renders (no Math.random)."],
  },
  {
    slug: "spotlight-card", name: "کارت نورانی", file: an("spotlight-card"),
    desc: "هاله‌ی نرمی که دنبال ماوس روی کارت حرکت می‌کنه و حاشیه را روشن می‌کنه.",
    usage: `import { SpotlightCard } from "@/components/animations/spotlight-card"\n\n<SpotlightCard><div className="p-5">…</div></SpotlightCard>`,
    promptBullets: ["Absolute layer with a radial-gradient at mouse coords; card has 1px padding so the glow shows on the border too.", "On mouseleave move the coords outside the card so it fades."],
  },
  {
    slug: "grid-reveal", name: "ظهور شبکه‌ای", file: an("grid-reveal"), css: KF.tileIn,
    desc: "کاشی‌هایی که به‌صورت موج قطری از بالا-راست ظاهر میشن.",
    usage: `import { GridReveal } from "@/components/animations/grid-reveal"\n\n<GridReveal cols={6} rows={3} />`,
    props: [{ name: "cols / rows", type: "number", default: "6 / 3", desc: "ابعاد شبکه." }, { name: "step", type: "number", default: "60", desc: "فاصله‌ی زمانی هر قطر." }],
    promptBullets: ["Each tile's delay = (row + col) × step; because column 0 is the right in RTL, the wave starts top-right.", "animation-fill-mode: both so tiles stay hidden until their turn."],
  },
  {
    slug: "text-reveal", name: "ظهور ماسکی", file: an("text-reveal"), css: KF.wipeIn, wide: true,
    desc: "خط‌های تیتر که یکی پس از دیگری از پشت یک ماسک، از راست بیرون می‌آن.",
    usage: `import { TextReveal } from "@/components/animations/text-reveal"\n\n<h1 className="text-4xl font-bold"><TextReveal lines={["زیرساخت پرداخت", "برای محصول دیجیتال شما"]} /></h1>`,
    props: [{ name: "lines", type: "string[]", desc: "هر عضو یک خطه." }, { name: "stagger", type: "number", default: "140", desc: "فاصله‌ی شروع خط‌ها (میلی‌ثانیه)." }, { name: "duration", type: "number", default: "900", desc: "مدت هر خط (میلی‌ثانیه)." }],
    notes: ["ماسک با clip-path هست نه overflow، برای همین دنباله‌ی حروفی مثل «ی» و «ج» بریده نمیشه."],
    promptBullets: ["Each line is a block span animating clip-path from inset(0 0 0 100%) to inset(0) so it uncovers from the right; add a small translateY.", "Delay = index × stagger; animation-fill-mode both; the full text goes in aria-label and the lines are aria-hidden."],
  },
  {
    slug: "highlight-text", name: "هایلایت متن", file: an("highlight-text"),
    desc: "خط ماژیکی که وقتی عبارت وارد دید شد، از راست زیرش کشیده میشه.",
    usage: `import { HighlightText } from "@/components/animations/highlight-text"\n\n<h2>قیمت‌ها <HighlightText>ساده و شفاف</HighlightText> هستند</h2>`,
    props: [{ name: "delay", type: "number", default: "0", desc: "تأخیر شروع (میلی‌ثانیه)." }],
    promptBullets: ["A linear-gradient background with background-size animating from 0% to 100% width and a fixed 0.5em height; background-position 100% 100% so it grows from the right.", "Trigger with IntersectionObserver at 0.6 threshold, once; box-decoration-break: clone for phrases that wrap."],
  },
  {
    slug: "gradient-text", name: "متن گرادیانی", file: an("gradient-text"), css: KF.gradientPan,
    desc: "گرادیان رنگ برند که آرام روی متن حرکت می‌کنه و متن انتخاب‌شدنی می‌مونه.",
    usage: `import { GradientText } from "@/components/animations/gradient-text"\n\n<h1 className="text-4xl font-bold"><GradientText>به‌زودی راه می‌افتیم</GradientText></h1>`,
    props: [{ name: "duration", type: "number", default: "6", desc: "ثانیه برای یک دور کامل." }],
    promptBullets: ["Five-stop gradient foreground→brand→foreground→brand→foreground at background-size 300% with background-clip:text; animate background-position from 0% to 150% for a seamless loop.", "Only the fill animates; no letter-spacing, no transform on the text."],
  },
  {
    slug: "flip-card", name: "کارت برگردان", file: an("flip-card"),
    desc: "کارتی که با هاور یا کلیک دور محور عمودی می‌چرخه و پشتش را نشان میده.",
    usage: `import { FlipCard } from "@/components/animations/flip-card"\n\n<FlipCard front={<div className="p-4">قیمت پلن</div>} back={<div className="p-4">۲۹۰٬۰۰۰ تومان / ماه</div>} />`,
    props: [{ name: "front / back", type: "ReactNode", desc: "دو روی کارت. اندازه از روی جلو گرفته میشه." }, { name: "trigger", type: '"hover" | "click"', default: '"hover"', desc: "با کلیک، کارت نقش دکمه می‌گیره و با Enter هم برمی‌گردد." }],
    promptBullets: ["Outer perspective:1200px; inner transform-style:preserve-3d with a 700ms rotateY(180deg) transition on hover/focus-within (or a click state).", "Both faces backface-visibility:hidden; the back is absolute inset-0 pre-rotated 180deg; click mode gets role=button, tabIndex 0 and aria-pressed."],
  },
  {
    slug: "animated-beam", name: "پرتو اتصال", file: an("animated-beam"), css: KF.beamTravel, wide: true,
    desc: "منحنی‌ای بین دو عنصر که نبض نور روی آن حرکت می‌کنه، برای نمایش یکپارچه‌سازی‌ها.",
    usage: `import { AnimatedBeam } from "@/components/animations/animated-beam"\n\nconst box = useRef(null), a = useRef(null), b = useRef(null)\n\n<div ref={box} className="relative">\n  <div ref={a}>…</div><div ref={b}>…</div>\n  <AnimatedBeam containerRef={box} fromRef={a} toRef={b} curvature={-40} />\n</div>`,
    props: [{ name: "containerRef / fromRef / toRef", type: "RefObject", desc: "ظرف relative و دو انتها." }, { name: "curvature", type: "number", default: "0", desc: "خمیدگی به پیکسل. مقدار مثبت رو به پایین خم میشه." }, { name: "duration / delay", type: "number", default: "4 / 0", desc: "ثانیه." }, { name: "reverse", type: "boolean", default: "false", desc: "نور از مقصد به مبدأ." }],
    notes: ["با pathLength=100 محاسبه‌ی dash از طول واقعی مسیر مستقله و نیازی به getTotalLength نیست.", "خط با z-index منفی زیر دو سر می‌نشینه. به ظرف relative isolate بدید تا پشت پس‌زمینه‌ی ظرف نره."],
    promptBullets: ["Measure the two ends relative to the container with getBoundingClientRect and draw a quadratic path; re-measure with ResizeObserver.", "SVG is absolute inset-0 with a negative z-index inside a relative isolate container so the line passes behind the endpoints. Three stacked paths: a faint base line, a wide low-opacity glow and a 2px brand stroke; the last two use pathLength=100, stroke-dasharray 28 100 and animate stroke-dashoffset 28 → -100; reverse via animation-direction."],
  },
  {
    slug: "confetti", name: "کاغذ رنگی", file: an("confetti"), css: KF.confetti,
    desc: "انفجار کاغذرنگی از پایین وسط، برای پایان پرداخت و ثبت‌نام.",
    usage: `import { Confetti } from "@/components/animations/confetti"\n\n<div className="relative overflow-hidden">\n  {paid && <Confetti key={paidAt} />}\n  …\n</div>`,
    props: [{ name: "count", type: "number", default: "60", desc: "تعداد تکه‌ها." }],
    notes: ["یک‌بار اجرا میشه. برای تکرار، key را عوض کنید تا دوباره mount بشه."],
    promptBullets: ["Each piece is a small span at bottom-center with per-piece CSS variables --cx, --cy, --cr set from a deterministic hash of the index (no Math.random) so SSR and client match.", "Keyframes rise to (--cx, --cy) at 60% then fall below the origin while fading; colors only from theme tokens (brand, foreground, success, warning, destructive)."],
  },
  {
    slug: "swipe-to-confirm", name: "کشیدن برای تأیید", file: an("swipe-to-confirm"), wide: true,
    desc: "دستگیره‌ای که از راست به چپ می‌کشید تا پرداخت تأیید بشه و اگر زود رها کنید، برمی‌گرده.",
    usage: `import { SwipeToConfirm } from "@/components/animations/swipe-to-confirm"\n\n<SwipeToConfirm label="برای پرداخت بکشید" doneLabel="پرداخت انجام شد" onConfirm={pay} />`,
    props: [{ name: "label / doneLabel", type: "string", desc: "متن قبل و بعد از تأیید." }, { name: "onConfirm", type: "() => void", desc: "وقتی دستگیره به انتها رسید." }],
    notes: ["برای کاربر کیبورد، Enter یا Space روی دستگیره مستقیم تأیید می‌کنه و کشیدن اجباری نیست."],
    promptBullets: ["Pointer events with setPointerCapture; progress = (dx × direction) / (trackWidth − handle) where direction is −1 under rtl; release at ≥ 0.9 confirms, otherwise snap back with a transition.", "Position the handle with inset-inline-start (calc from progress) so it starts at the RTL start; label fades as progress grows; touch-none on the handle."],
  },
  {
    slug: "terminal", name: "ترمینال", file: an("terminal"), wide: true,
    desc: "دستورهایی که حرف‌به‌حرف تایپ میشن و خروجی‌شون زیرشون چاپ میشه، با خروجی فارسی راست‌چین.",
    usage: `import { Terminal } from "@/components/animations/terminal"\n\n<Terminal lines={[\n  { type: "cmd", text: "npx vibefarsi add otp-field" },\n  { type: "ok", text: "otp-field به components/ui اضافه شد" },\n]} />`,
    props: [{ name: "lines", type: '{ type: "cmd" | "out" | "ok" | "err"; text }[]', desc: "به ترتیب اجرا." }, { name: "speed", type: "number", default: "45", desc: "میلی‌ثانیه برای هر حرف." }, { name: "title", type: "string", default: '"ترمینال"', desc: "عنوان نوار بالا." }],
    promptBullets: ["State: number of finished lines and typed characters of the current command; a single timeout advances one step (type a character, or print the next line).", "Command rows are dir=ltr with a $ prompt and a pulsing block cursor; output rows keep the document's rtl and colour by type (✓ success, ✗ destructive); start via IntersectionObserver."],
  },
  {
    slug: "card-stack", name: "پشته‌ی کارت", file: an("card-stack"),
    desc: "کارت‌هایی روی هم که هر چند ثانیه کارت جلویی به ته صف میره، مناسب نظرات مشتری.",
    usage: `import { CardStack } from "@/components/animations/card-stack"\n\n<CardStack className="h-44" items={reviews.map((r) => <Review key={r.id} {...r} />)} />`,
    props: [{ name: "items", type: "ReactNode[]", desc: "کارت‌ها به ترتیب اولیه." }, { name: "interval", type: "number", default: "3200", desc: "میلی‌ثانیه بین جابه‌جایی‌ها." }, { name: "offset / scale", type: "number", default: "12 / 0.05", desc: "جابه‌جایی و کوچک‌شدن هر لایه." }],
    promptBullets: ["Keep an order array and rotate it on an interval; each card is absolute inset-0 with transform translateY(depth × offset) scale(1 − depth × scale), origin top, and z-index by depth.", "Pause the interval on hover; cards deeper than two fade out; only the front card is not aria-hidden.", "Small SVG countdown ring at the top-end corner uses the draw keyframe over `interval` ms and remounts each cycle; animation-play-state pauses on hover."],
  },
  {
    slug: "morph-button", name: "دکمه‌ی سه‌حالته", file: an("morph-button"),
    desc: "یک دکمه با سه حالت عادی، در حال انجام و انجام شد، که حالت‌ها درجا محو میشن و عرضش نمی‌پره.",
    usage: `import { MorphButton } from "@/components/animations/morph-button"\n\n<MorphButton onAction={() => subscribe(email)} loadingText="در حال ثبت…" doneText="ثبت شد">خبرم کن</MorphButton>`,
    props: [{ name: "onAction", type: "() => Promise<unknown> | void", desc: "تا resolve بشه، حالت «در حال انجام» می‌مونه." }, { name: "loadingText / doneText", type: "string", desc: "متن دو حالت بعدی." }, { name: "resetAfter", type: "number", default: "2200", desc: "میلی‌ثانیه تا برگشت به حالت عادی. صفر یعنی هرگز." }],
    promptBullets: ["inline-grid button where all three states occupy the same cell (col-start-1 row-start-1) so the width is the widest state from the first render; inactive states are opacity 0, translateY 8px and pointer-events none.", "aria-live=polite and aria-busy while loading; disabled outside idle; background switches to success on done."],
  },
  {
    slug: "compare-slider", name: "مقایسه‌ی قبل و بعد", file: an("compare-slider"), wide: true,
    desc: "دو لایه با یک خط جداکننده‌ی کشیدنی که «قبل» سمت راسته و با کیبورد هم جابه‌جا میشه.",
    usage: `import { CompareSlider } from "@/components/animations/compare-slider"\n\n<CompareSlider before={<img src="/old.png" alt="" />} after={<img src="/new.png" alt="" />} />`,
    props: [{ name: "before / after", type: "ReactNode", desc: "دو لایه. اندازه از «قبل» گرفته میشه." }, { name: "beforeLabel / afterLabel", type: "string", default: '"قبل" / "بعد"', desc: "برچسب گوشه‌ها." }, { name: "defaultValue", type: "number", default: "50", desc: "درصد اولیه از سمت راست." }],
    promptBullets: ["The after layer is absolute and clipped with clip-path: inset(0 v% 0 0) so the divider sits v% from the right (the RTL start); the before layer is in normal flow and gives the box its size.", "The control is a full-size transparent <input type=range> (browsers mirror it under rtl), so dragging, clicking and arrow keys all work; aria-valuetext with Persian digits and «٪»."],
  },
  {
    slug: "scratch-card", name: "کارت خراشیدنی", file: an("scratch-card"),
    desc: "روکشی که با انگشت یا ماوس می‌خراشید تا کد تخفیف زیرش پیدا بشه و وقتی نصفش رفت، خودش پاک میشه.",
    usage: `import { ScratchCard } from "@/components/animations/scratch-card"\n\n<ScratchCard coverText="بخراشید" onReveal={track}>\n  <div className="p-6 text-center">کد تخفیف: <b dir="ltr">NOWRUZ40</b></div>\n</ScratchCard>`,
    props: [{ name: "coverText", type: "string", default: '"اینجا را بخراشید"', desc: "متن روی روکش." }, { name: "brushSize", type: "number", default: "22", desc: "شعاع قلم به پیکسل." }, { name: "threshold", type: "number", default: "0.45", desc: "چه کسری پاک بشه تا کامل باز بشه." }],
    promptBullets: ["A canvas over the content, scaled by devicePixelRatio, painted with the --secondary token, diagonal stripes and the cover text (ctx.direction = rtl); pointer moves with buttons pressed erase circles using destination-out.", "Every ~10 moves sample alpha of every 8th pixel; past the threshold fade the canvas out and call onReveal; touch-none, role=button and Enter reveals for keyboard users."],
  },
  {
    slug: "sparkles", name: "جرقه", file: an("sparkles"), css: KF.sparkle,
    desc: "ستاره‌های ریزی که دور یک کلمه یا نشان چشمک می‌زنن، برای «جدید» و «ویژه».",
    usage: `import { Sparkles } from "@/components/animations/sparkles"\n\n<Sparkles><Badge variant="brand">جدید</Badge></Sparkles>`,
    props: [{ name: "count", type: "number", default: "7", desc: "تعداد جرقه‌ها." }],
    promptBullets: ["Inline-block relative wrapper; each sparkle is a tiny absolutely-positioned four-point star SVG in the brand colour, placed by a deterministic hash of its index (no Math.random).", "Keyframes scale 0 → 1 → 0 with a 90deg rotation and per-sparkle duration/delay so they never blink in sync."],
  },
  {
    slug: "scroll-progress", name: "پیشرفت خواندن", file: an("scroll-progress"), wide: true,
    desc: "نوار باریکی بالای صفحه که با اسکرول از راست پر میشه، برای مقاله و مستندات.",
    usage: `import { ScrollProgress } from "@/components/animations/scroll-progress"\n\n// app/blog/[slug]/page.tsx\n<ScrollProgress />\n\n// or inside a scroll box\n<div ref={box} className="overflow-auto"><ScrollProgress targetRef={box} className="sticky" />…</div>`,
    props: [{ name: "targetRef", type: "RefObject<HTMLElement>", desc: "جعبه‌ی اسکرول‌شونده. بدون آن، خودِ صفحه حساب میشه." }],
    promptBullets: ["Listen to scroll (passive) on the target or window and set progress = scrollTop / (scrollHeight − clientHeight); transform: scaleX(progress) with transform-origin right so it grows from the RTL start.", "role=progressbar with aria-valuenow; fixed inset-x-0 top-0 by default, overridable via className."],
  },
  {
    slug: "pulse-button", name: "دکمه‌ی ضربان‌دار", file: an("pulse-button"), css: KF.pulseRing, registryDeps: ["button"],
    desc: "دو حلقه‌ای که پشت دکمه باز میشن تا عمل اصلی صفحه به چشم بیاید.",
    usage: `import { PulseButton } from "@/components/animations/pulse-button"\n\n<PulseButton size="lg">شروع رایگان</PulseButton>`,
    promptBullets: ["Wrap the Button in a relative span with two absolute inset-0 layers in primary/40 that animate scale 1 → 1.4 and opacity 0.6 → 0, offset by half the period.", "Layers copy the button's radius by size; one instance per page."],
  },
  {
    slug: "cursor-follow", name: "نشانگر سفارشی", file: an("cursor-follow"),
    desc: "نشانگر و برچسبی که داخل یک ناحیه جای نشانگر سیستم را می‌گیرن، مناسب پیش‌نمایش محصول.",
    usage: `import { CursorFollow } from "@/components/animations/cursor-follow"\n\n<CursorFollow label="مشاهده" className="h-48">\n  <div className="flex h-full items-center justify-center">ماوس را اینجا بیاورید</div>\n</CursorFollow>`,
    props: [
      { name: "label", type: "ReactNode", desc: "متن یا عنصر کنار نشانگر." },
      { name: "labelOffset", type: "{ x; y }", default: "{ x: 18, y: 14 }", desc: "جابه‌جایی برچسب از نوک نشانگر." },
    ],
    notes: ["روی لمس و اشاره‌گر درشت خاموش می‌مونه؛ فقط با ماوس ظاهر میشه."],
    promptBullets: ["Track pointer relative to the container; render an absolute SVG cursor and optional label at those coords; set cursor-none only when (pointer: fine).", "Hide on mouseleave; no-op on touch / coarse pointers."],
  },
  {
    slug: "number-wheel", name: "چرخ عدد", file: an("number-wheel"), css: KF.particleBurst, wide: true,
    desc: "حلقه‌ی عمودی اعداد فارسی که تا مقدار هدف می‌چرخه و ستاره‌اش پر میشه.",
    usage: `import { NumberWheel } from "@/components/animations/number-wheel"\n\n<NumberWheel value={2400} step={100} />`,
    props: [
      { name: "value", type: "number", desc: "مقدار نهایی." },
      { name: "step", type: "number", default: "100", desc: "گام بین ردیف‌ها." },
      { name: "sideItemsCount", type: "number", default: "2", desc: "ردیف‌های بالا و پایین هایلایت." },
      { name: "duration / delay", type: "number", default: "1800 / 200", desc: "میلی‌ثانیه." },
      { name: "withStar", type: "boolean", default: "true", desc: "ستاره‌ی پرشونده و جرقه در پایان." },
    ],
    promptBullets: ["Build a stepped list around the rounded target; rAF ease-out scrolls translateY so the target lands in the centre highlight.", "Persian digits via faNumber; star fill uses clip-path inset from the top; on complete, burst particles with the particle-burst keyframe and --burst-x/y."],
  },
  {
    slug: "pin-list", name: "فهرست سنجاق", file: an("pin-list"), wide: true,
    desc: "آیتم‌هایی که با کلیک بین بخش سنجاق‌شده و همه جابه‌جا میشن و با FLIP نرم حرکت می‌کنن.",
    usage: `import { PinList } from "@/components/animations/pin-list"\n\n<PinList items={[{ id: "1", name: "خانه", info: "داشبورد", icon: Home, pinned: true }, …]} />`,
    props: [
      { name: "items", type: "PinListItem[]", desc: "id، name، info، icon، pinned." },
      { name: "labels", type: "{ pinned?; unpinned? }", default: '"سنجاق‌شده" / "همه"', desc: "عنوان دو بخش." },
      { name: "onChange", type: "(items) => void", desc: "بعد از هر سنجاق یا برداشتن سنجاق." },
    ],
    promptBullets: ["Measure each [data-pin-id] rect before the state change; after layout, invert with translate(dx,dy) then transition transform to none (FLIP).", "Pinned items show a filled pin; unpinned reveal the pin on hover/focus; click toggles and reorders (pinned to end, unpinned to start)."],
  },
  {
    slug: "radial-intro", name: "معرفی شعاعی", file: an("radial-intro"), css: KF.radialOrbit,
    desc: "آواتارهایی که از مرکز باز میشن، روی مدار می‌نشینن و بعد با حفظ راست‌ایستایی می‌چرخن.",
    usage: `import { RadialIntro } from "@/components/animations/radial-intro"\n\n<RadialIntro items={[{ id: "1", name: "سارا", src: "/avatars/sara.jpg" }, { id: "2", name: "علی", src: "/avatars/ali.jpg" }, { id: "3", name: "مینا", src: "/avatars/mina.jpg" }, { id: "4", name: "رضا", src: "/avatars/reza.jpg" }, { id: "5", name: "نگار", src: "/avatars/negar.jpg" }]} />`,
    props: [
      { name: "items", type: "{ id; name; src }[]", desc: "آواتارها به ترتیب مدار." },
      { name: "stageSize / imageSize", type: "number", default: "280 / 52", desc: "قطر صحنه و آواتار." },
      { name: "duration", type: "number", default: "28", desc: "ثانیه برای یک دور کامل." },
    ],
    promptBullets: ["Phased: idle (stacked centre) → lift (fade in) → place (rotate arms to equal angles) → spin (radial-orbit + radial-counter so faces stay upright).", "Set --start-angle per arm and --orbit-r on the stage; dashed ring marks the orbit."],
  },
  {
    slug: "text-loop", name: "حلقه‌ی متن", file: an("text-loop"), wide: true,
    registryDeps: ["svg-text-path-rtl"],
    desc: "متن روی مسیر SVG (موج، قوس، دایره، …) می‌چرخه؛ نوار رنگی مسیر را نشان میده و با هاور متوقف میشه.",
    usage: `import { TextLoop } from "@/components/animations/text-loop"\n\n<TextLoop text="وایب‌فارسی" shape="wave" ribbon />`,
    props: [
      { name: "text / separator", type: "string", default: '"وایب‌فارسی" / "·"', desc: "متن و جداکننده‌ی تکرار." },
      { name: "shape", type: '"wave" | "line" | "arch" | "circle" | "infinity"', default: '"wave"', desc: "شکل مسیر. یا path سفارشی." },
      { name: "speed", type: "number", default: "90", desc: "پیکسل بر ثانیه روی مسیر." },
      { name: "ribbon / ribbonWidth", type: "boolean / number", default: "true / 64", desc: "نوار stroke-brand پشت متن." },
      { name: "fontSize", type: "number", default: "36", desc: "اندازه‌ی فونت در واحد viewBox؛ کمی تنظیم میشه تا تکرارها دقیقاً مسیر را پر کنن." },
      { name: "pauseOnHover", type: "boolean", default: "true", desc: "با هاور متوقف میشه." },
    ],
    promptBullets: ["Place pre-shaped glyphs with getPointAtLength (no <textPath>); animate a distance offset with requestAnimationFrame so Safari is not hit by textPath shaping bugs or negative startOffset.", "Run copy through forSvgTextPath (presentation forms + RTL visual order). Open paths keep an extra tile of lead-in; closed paths wrap along the path length.", "Scale glyph widths so a whole number of tiles matches the path length; paint into a <g> via DOM updates (not React state) at 60fps.", "Text on the ribbon uses fill-brand-foreground over stroke-brand; respect prefers-reduced-motion by freezing at offset 0."],
  },
  {
    slug: "curved-loop", name: "متن خمیده", file: an("curved-loop"), wide: true,
    registryDeps: ["svg-text-path-rtl"],
    desc: "مارکی روی یک قوس که می‌تونید با کشیدن بکشیدش؛ جهت بعد از رها کردن از سرعت دست می‌آد.",
    usage: `import { CurvedLoop } from "@/components/animations/curved-loop"\n\n<CurvedLoop text="وایب‌فارسی · راست‌چین · فارسی" curveAmount={120} />`,
    props: [
      { name: "text", type: "string", desc: "متن مارکی. فاصله‌ی انتهایی خودکار اضافه میشه." },
      { name: "speed", type: "number", default: "1.2", desc: "پیکسل در هر فریم (روی ۶۰ فریم؛ با زمان مقیاس میشه تا روی هر نمایشگری یکسان باشه)." },
      { name: "curveAmount", type: "number", default: "80", desc: "عمق قوس درجه دو؛ منفی یعنی قوس رو به بالا." },
      { name: "fontSize", type: "number", default: "72", desc: "اندازه‌ی فونت در واحد viewBox (عرض ۱۴۴۰)." },
      { name: "direction", type: '"left" | "right"', default: '"left"', desc: "جهت پیش‌فرض حرکت." },
      { name: "interactive", type: "boolean", default: "true", desc: "اجازه‌ی کشیدن با اشاره‌گر." },
    ],
    promptBullets: ["Quadratic path across a 1440-wide viewBox whose height grows with curveAmount; lay forSvgTextPath glyphs with getPointAtLength and wrap the distance offset in [0, spacing).", "No <textPath> (Safari breaks Arabic shaping/bidi and negative startOffset); paint glyphs into a <g> via DOM updates.", "Pointer drag (scaled from screen px to viewBox units) updates the offset and sets direction from release velocity; touch-pan-y so vertical scroll still works.", "No text-transform uppercase; fill from text-foreground token; freeze under prefers-reduced-motion."],
  },
  {
    slug: "number-pop", name: "ظهور رقم‌ها", file: an("number-pop"), css: KF.digitPop,
    desc: "هر بار عدد عوض میشه، رقم‌هاش یکی‌یکی از سمت یکان با کمی تاری بالا می‌آن.",
    usage: `import { NumberPop } from "@/components/animations/number-pop"\n\n<NumberPop value={price} unit="تومان" className="text-3xl font-bold" />`,
    props: [
      { name: "value", type: "number", desc: "عدد فعلی. با هر تغییر، رقم‌ها دوباره ظاهر میشن." },
      { name: "format", type: "(n) => string", default: "faNumber", desc: "قالب خودِ عدد؛ پیش‌فرض اعداد فارسی با جداکننده‌ی هزارگان." },
      { name: "stagger", type: "number", default: "30", desc: "فاصله‌ی زمانی بین رقم‌های همسایه به میلی‌ثانیه." },
      { name: "from", type: '"bottom" | "top"', default: '"bottom"', desc: "رقم‌ها از پایین بیان یا از بالا." },
      { name: "unit", type: "ReactNode", desc: "واحد، بیرون از جعبه‌ی عدد تا با تغییر تعداد رقم‌ها جابه‌جا نشه." },
    ],
    notes: ["برخلاف شمارنده و شماره‌انداز که مقدار را می‌شمرن، این‌جا فقط ظاهر شدن عدد جدید انیمیت میشه، پس برای قیمت و موجودی که ناگهانی عوض میشن مناسب‌تره."],
    promptBullets: ["Split the formatted Persian number into characters; keep the digit row dir=ltr so the most-significant digit stays on the left inside an RTL line.", "Each digit animates opacity + blur(2px) + translateY(8px) with a bouncy cubic-bezier(0.34,1.45,0.64,1) over 500ms; animation-delay grows from the ones digit outward (last index first).", "Remount the digit row (key = formatted text) on every value change; render the unit outside the row."],
  },
  {
    slug: "notification-badge", name: "نشان اعلان", file: an("notification-badge"), css: KF.badge,
    desc: "نشان از دل آیکون به‌صورت مورب بیرون می‌آد و نقطه‌ش با فنر باز میشه؛ خود آیکون فقط یک تکان کوتاه می‌خوره.",
    usage: `import { NotificationBadge } from "@/components/animations/notification-badge"\n\n<NotificationBadge show={unread > 0} count={unread}>\n  <Bell className="size-5" />\n</NotificationBadge>`,
    props: [
      { name: "show", type: "boolean", desc: "نمایش یا پنهان کردن نشان." },
      { name: "count", type: "number", desc: "عدد داخل نشان با اعداد فارسی؛ بالای ۹۹ میشه «۹۹+». اگر ندید، فقط یک نقطه نشان داده میشه." },
      { name: "ring", type: "boolean", default: "true", desc: "آیکون هنگام ظاهر شدن نشان کمی تکان بخوره." },
    ],
    notes: ["نشان روی گوشه‌ی انتهایی خط (inline-end) می‌شینه، یعنی در فارسی بالا-چپ آیکون، و جهت سُر خوردنش هم با rtl: برعکس میشه."],
    promptBullets: ["Badge wrapper is absolutely positioned at top/inline-end with a CSS variable --bx that flips sign under [dir=rtl]; on show it plays a 260ms keyframe from translate(var(--bx), 12px) to 0.", "The dot itself transitions scale 0→1, opacity and blur(2px)→0 with cubic-bezier(0.34,1.36,0.64,1) over 500ms; closing is 180ms with a standard ease.", "Optional bell-ring keyframe (rotate 14 → -10 → 6 → -3 → 1 deg, origin top) on the icon wrapper, keyed so it replays each time show turns true.", "Persian digits inside the badge; ring-2 ring-background so it separates from the icon."],
  },
  {
    slug: "text-swap", name: "تعویض متن", file: an("text-swap"), css: KF.swap,
    desc: "برچسب وضعیت سر جاش عوض میشه: متن قبلی با کمی تاری بالا میره و متن جدید از پایین می‌آد.",
    usage: `import { TextSwap } from "@/components/animations/text-swap"\n\nconst labels = ["ذخیره", "در حال ذخیره…", "ذخیره شد"]\n<Button><TextSwap value={labels[step]} options={labels} /></Button>`,
    props: [
      { name: "value", type: "string", desc: "متن فعلی؛ هر تغییرش انیمیت میشه." },
      { name: "options", type: "string[]", desc: "همه‌ی برچسب‌های ممکن تا عرض به اندازه‌ی بلندترین رزرو بشه و دکمه نپره." },
      { name: "duration", type: "number", default: "150", desc: "میلی‌ثانیه برای هر نیمه‌ی جابه‌جایی." },
      { name: "direction", type: '"up" | "down"', default: '"up"', desc: "جهت خروج متن قبلی." },
    ],
    promptBullets: ["Keep the previous value in state (set during render when the prop changes) and render it as an outgoing copy in the same grid cell with the swap-out keyframe (to translateY(-4px) blur(2px) opacity 0) while the new value mounts (key = value) with swap-in from +4px; both run at once over `duration`, then drop the outgoing copy on a timeout.", "--swap-y flips sign for direction=down.", "Reserve width with an invisible copy of the longest option in the same grid cell; aria-live=polite; no layout shift."],
  },
  {
    slug: "panel-reveal", name: "ظهور پنل", file: an("panel-reveal"),
    desc: "پنلی که با کمی تاری سر جاش سُر می‌خوره؛ در فارسی از سمت راست می‌آد و وقتی بسته‌ست از دسترس کیبورد هم خارجه.",
    usage: `import { PanelReveal } from "@/components/animations/panel-reveal"\n\n<PanelReveal open={open} from="start" className="rounded-xl border p-4">\n  …\n</PanelReveal>`,
    props: [
      { name: "open", type: "boolean", desc: "باز یا بسته." },
      { name: "from", type: '"start" | "end" | "bottom" | "top"', default: '"start"', desc: "جهت ورود. start در فارسی یعنی از راست." },
    ],
    notes: ["وقتی بسته‌ست، ویژگی inert روی پنل می‌شینه تا نه با Tab بهش برسید و نه صفحه‌خوان چیزی از داخلش بخونه."],
    promptBullets: ["Transition transform + opacity + filter(blur 2px) with cubic-bezier(0.22,1,0.36,1); 400ms open, 350ms close.", "Offsets are CSS variables (--px/--py) whose sign flips under [dir=rtl] for start/end, so the panel always enters from the reading edge.", "Closed state sets inert and aria-hidden."],
  },
  {
    slug: "page-slide", name: "جابه‌جایی صفحه", file: an("page-slide"), wide: true,
    desc: "بین چند صفحه (فهرست و جزئیات، قدم اول و دوم) جابه‌جا میشه؛ صفحه‌ی بعدی در فارسی از چپ می‌آد و قبلی به راست میره.",
    usage: `import { PageSlide } from "@/components/animations/page-slide"\n\n<PageSlide index={step} pages={[<List key="l" />, <Detail key="d" />]} />`,
    props: [
      { name: "index", type: "number", desc: "شماره‌ی صفحه‌ی فعال." },
      { name: "pages", type: "ReactNode[]", desc: "صفحه‌ها به ترتیب." },
      { name: "distance", type: "number", default: "12", desc: "پیکسل جابه‌جایی." },
    ],
    notes: ["صفحه‌ها در یک خانه‌ی grid روی هم می‌شینن، پس ارتفاع ظرف همیشه به اندازه‌ی بلندترین صفحه‌ست و لازم نیست خودتون ارتفاع بدید."],
    promptBullets: ["All pages share one grid cell (col-start-1 row-start-1); inactive pages are opacity 0, blur(3px) and inert.", "Pages after the active index sit at translateX(+distance * var(--fwd)), earlier ones at -distance; --fwd is 1 in LTR and -1 under [dir=rtl] so forward always moves against the reading direction.", "250ms transitions with cubic-bezier(0.22,1,0.36,1); the entering page gets a 40ms delay."],
  },
  {
    slug: "icon-swap", name: "تعویض آیکون", file: an("icon-swap"),
    desc: "دو آیکون در یک جایگاه؛ فعال با بزرگ شدن و رفع تاری می‌آد و دیگری کوچک و تار میشه. با rotate یک‌چهارم دور هم می‌چرخن.",
    usage: `import { IconSwap } from "@/components/animations/icon-swap"\n\n<IconSwap state={open ? "b" : "a"} a={<Menu />} b={<X />} rotate />`,
    props: [
      { name: "state", type: '"a" | "b"', desc: "کدام آیکون فعاله." },
      { name: "a / b", type: "ReactNode", desc: "دو آیکون." },
      { name: "rotate", type: "boolean", default: "false", desc: "چرخش ۹۰ درجه هنگام تعویض؛ برای منو و بستن مناسبه." },
      { name: "duration", type: "number", default: "250", desc: "میلی‌ثانیه." },
    ],
    promptBullets: ["Both icons in one inline-grid cell; the inactive one is opacity 0, blur(2px), scale(0.5) and optionally rotate(±90deg).", "Transition opacity, filter and transform together with ease-in-out over 250ms; aria-hidden on the inactive icon."],
  },
  {
    slug: "avatar-hover", name: "هاور آواتارها", file: an("avatar-hover"), registryDeps: ["avatar"],
    desc: "آواتاری که روش می‌رید بالا می‌پره و همسایه‌هاش با شدت کمتر دنبالش می‌آن؛ موقع رفتن همه با یک فنر برمی‌گردن و اسم بالای آواتار فعال شناور میشه.",
    usage: `import { AvatarHover } from "@/components/animations/avatar-hover"\n\n<AvatarHover people={[{ name: "سارا", src: "/avatars/sara.jpg" }, { name: "علی" }]} />`,
    props: [
      { name: "people", type: "{ name; src? }[]", desc: "افراد به ترتیب نمایش." },
      { name: "lift", type: "number", default: "8", desc: "پیکسل بالا رفتن آواتار فعال." },
      { name: "falloff", type: "number", default: "0.45", desc: "هر همسایه چه کسری از قبلی بالا بره." },
      { name: "size", type: '"sm" | "md" | "lg"', default: '"md"', desc: "اندازه‌ی آواتار." },
    ],
    promptBullets: ["Per item: transform translateY(lift * falloff^|i - active|) then scale(1.08) on the active one; the transition timing-function is chosen per phase — cubic-bezier(0.22,1,0.36,1) in, cubic-bezier(0.34,3.85,0.64,1) on leave for the overshoot.", "Name label absolutely positioned above the active avatar (left:50% + translateX(-50%) so it centres in both directions), fading in with a 4px rise.", "Overlap with negative margin-inline-start; raise the active z-index."],
  },
  {
    slug: "error-shake", name: "لرزش خطا", file: an("error-shake"), css: KF.errorShake,
    desc: "دور فیلد را بگیرید؛ وقتی خطا می‌آد جعبه با لرزشی که کم‌کم آروم میشه تکان می‌خوره، حلقه‌ی قرمز و پیام ظاهر میشن و بعد چند ثانیه خودشون می‌رن.",
    usage: `import { ErrorShake } from "@/components/animations/error-shake"\n\n<ErrorShake error={error}>\n  <Input value={code} onChange={…} />\n</ErrorShake>`,
    props: [
      { name: "error", type: "string | null", desc: "متن خطا؛ هر بار مقدار جدید بگیره لرزش دوباره پخش میشه." },
      { name: "revertAfter", type: "number", default: "3000", desc: "میلی‌ثانیه تا برگشت خودکار به حالت عادی؛ صفر یعنی بمونه." },
      { name: "onRevert", type: "() => void", desc: "وقتی حالت خطا خودش پاک شد صدا زده میشه تا state خودتون را هم خالی کنید." },
    ],
    notes: ["فرزندها هیچ‌وقت دوباره mount نمیشن، پس فوکوس و مقدار ورودی سر جاش می‌مونه. لرزش با حذف و اضافه‌ی animation روی خود عنصر تکرار میشه."],
    promptBullets: ["Wrapper div gets an inline animation `error-shake 0.4s linear` re-applied via style.animation='none' → reflow → set, so it replays without remounting children.", "Keyframes are a decaying swing (8, -7, 5, -3 px) with a per-stop cubic-bezier(0.36,0.07,0.19,0.97).", "Error ring is a box-shadow (1px destructive + 4px 18% destructive) transitioned 150ms in / 280ms out; the message uses opacity + a delayed visibility so it stays painted during fade-out; role=alert.", "Auto-revert with setTimeout(revertAfter) and cleanup."],
  },
  {
    slug: "clear-input", name: "پاک کردن با محو شدن", file: an("clear-input"), css: KF.clear, wide: true,
    desc: "فیلد جستجویی که با زدن ×، کلمه‌هاش یکی‌یکی از سمت راست با کمی نور و تاری پایین می‌ریزن و placeholder از بالا برمی‌گرده.",
    usage: `import { ClearInput } from "@/components/animations/clear-input"\n\nconst [q, setQ] = useState("")\n<ClearInput value={q} onChange={setQ} placeholder="جستجوی محصول…" />`,
    props: [
      { name: "value / onChange", type: "string / (v) => void", desc: "کنترل‌شده؛ پاک کردن هم onChange('') را صدا می‌زنه." },
      { name: "placeholder", type: "string", default: '"جستجو…"', desc: "متن راهنما که بعد از پاک شدن از بالا می‌افته." },
    ],
    notes: ["کلمه‌ها به‌صورت کامل انیمیت میشن، نه حرف‌به‌حرف، پس اتصال حروف فارسی به هم نمی‌ریزه. Escape هم فیلد را پاک می‌کنه."],
    promptBullets: ["On clear: immediately set value to '' and render a pointer-events-none ghost layer over the input with one span per word of the old value; each span plays word-dissolve (translateY 12px, blur 2px, fade, text-shadow glow at 30%) with a 45ms stagger from the first word.", "Hide the real placeholder while a second ghost plays placeholder-drop from -10px after the last word; then drop both ghosts.", "Clear button uses onMouseDown preventDefault so focus stays in the input; it scales/fades in only when there is a value."],
  },
  {
    slug: "skeleton-reveal", name: "ظهور از اسکلت", file: an("skeleton-reveal"), css: KF.pulse, registryDeps: ["skeleton"],
    desc: "اسکلت و محتوای واقعی در یک جایگاه؛ اسکلت می‌تپه و وقتی داده رسید تار میشه و محتوا با رفع تاری و کمی بالا آمدن جاش را می‌گیره.",
    usage: `import { SkeletonReveal } from "@/components/animations/skeleton-reveal"\n\n<SkeletonReveal loading={isLoading} skeleton={<SkeletonRow />}>\n  <Row data={data} />\n</SkeletonReveal>`,
    props: [
      { name: "loading", type: "boolean", desc: "تا وقتی true باشه اسکلت نشان داده میشه." },
      { name: "skeleton", type: "ReactNode", desc: "اسکلت هم‌شکل با محتوا." },
      { name: "duration", type: "number", default: "400", desc: "میلی‌ثانیه‌ی جابه‌جایی." },
    ],
    notes: ["چون هر دو لایه از اول در یک خانه‌ی grid هستن، هیچ layout shift اتفاق نمی‌افته و ارتفاع از بلندترین لایه می‌آد."],
    promptBullets: ["Both layers in one grid cell; skeleton layer transitions opacity 1→0 and blur 0→2px while the content layer does the reverse plus translateY(4px)→0, all over 400ms ease-in-out.", "Pulse (pulse-soft keyframes) sits on an inner wrapper of the skeleton, not on the transitioned layer.", "Content gets inert while loading; aria-busy on the wrapper."],
  },
  {
    slug: "fab-morph", name: "دکمه‌ی شناور بازشونده", file: an("fab-morph"),
    desc: "دکمه‌ی گرد + خودش تبدیل به منو میشه: عرض، ارتفاع و گردی گوشه‌ها کش می‌آن، علامت + به × می‌چرخه و گزینه‌ها پشت سر هم می‌آن.",
    usage: `import { FabMorph } from "@/components/animations/fab-morph"\n\n<FabMorph items={[{ label: "پست جدید", icon: <PenLine /> }, { label: "آپلود عکس", icon: <Image /> }]} />`,
    props: [
      { name: "items", type: "{ label; icon?; onSelect? }[]", desc: "گزینه‌های منو." },
      { name: "open / onOpenChange", type: "boolean / (o) => void", desc: "اختیاری برای کنترل از بیرون." },
      { name: "width", type: "number", default: "200", desc: "عرض منوی باز؛ ارتفاع از تعداد گزینه‌ها حساب میشه." },
    ],
    notes: ["دکمه به گوشه‌ی انتهایی خط چسبیده، پس در فارسی پایین‌چپ می‌شینه و منو به سمت بالا و راست باز میشه. کلیک بیرون و Escape می‌بندنش."],
    promptBullets: ["The anchor is sized to the open footprint; the surface is absolute bottom/inline-end and transitions width 44→width, height 44→auto-computed and border-radius 22→16px; open uses cubic-bezier(0.34,1.3,0.64,1) 300ms, close cubic-bezier(0.22,1,0.36,1) 220ms.", "Items slide in from --sx (12px, sign flipped under [dir=rtl]) with blur(2px)→0 and a 40ms per-item delay; the trigger stays in the corner and rotates the plus 135deg into an ×.", "overflow:hidden on the surface clips items during the morph; aria-expanded on the trigger; outside pointerdown and Escape close."],
  },
  {
    slug: "like-button", name: "دکمه‌ی پسندیدن", file: an("like-button"), css: KF.like,
    desc: "قلب پر میشه و می‌پره، هشت ذره‌ی ریز به اطراف می‌پاشن و شمارنده با ظهور عدد جدید بالا میره؛ برداشتن لایک فقط رنگ را برمی‌گردونه.",
    usage: `import { LikeButton } from "@/components/animations/like-button"\n\n<LikeButton count={128} onChange={(liked) => …} />`,
    props: [
      { name: "liked / defaultLiked", type: "boolean", desc: "کنترل‌شده یا اولیه." },
      { name: "count", type: "number", desc: "تعداد لایک بقیه؛ لایک خود کاربر روش اضافه میشه." },
      { name: "onChange", type: "(liked) => void", desc: "بعد از هر تغییر." },
    ],
    promptBullets: ["Heart fill transitions transparent→currentColor over 300ms; the pop keyframe (1 → 0.8 → 1.25 → 1) runs on a wrapper span keyed per like, never on the svg.", "Eight particle <i> elements with per-particle --px/--py/size/delay from a seeded PRNG (mulberry32) so each burst differs; like-burst keyframe translates to (--px, --py) and fades.", "Count re-pops with digit-pop (direction up on like, down on unlike) in a grid cell; aria-pressed on the button."],
  },
  {
    slug: "arrow-link", name: "لینک با فلش", file: an("arrow-link"),
    desc: "لینک «بیشتر بخوانید» که فلشش در فارسی رو به چپ نگاه می‌کنه؛ با هاور به همان سمت سُر می‌خوره، دو بازوش باز میشن و یک خط از پشت کشیده میشه تا فلش کامل بشه.",
    usage: `import { ArrowLink } from "@/components/animations/arrow-link"\n\n<ArrowLink href="/docs">بیشتر بخوانید</ArrowLink>`,
    props: [{ name: "href", type: "string", desc: "مقصد؛ بقیه‌ی props به <a> می‌رسن." }],
    notes: ["فقط با CSS کار می‌کنه. کیبورد و لمس همان حالت ساکن را می‌بینن، پس هیچ اطلاعی فقط با حرکت منتقل نمیشه."],
    promptBullets: ["Set --flip:1 and under [dir=rtl] --flip:-1; the svg is scaleX(var(--flip)) so the chevron points along the reading direction and the hover translateX is calc(3px * var(--flip)).", "Two arm paths with transform-origin at the apex (10px 8px, transform-box: view-box) rotate ∓8deg on hover; a shaft path uses stroke-dasharray/dashoffset 7→0 so it draws in.", "In: 200ms, out: 300ms, cubic-bezier(0.22,1,0.36,1)."],
  },
  {
    slug: "thinking-states", name: "وضعیت فکر کردن", file: an("thinking-states"), css: KF.think,
    desc: "خط وضعیت هوش مصنوعی: تا وقتی یک حالت پابرجاست نوری روش می‌گذره و وقتی عوض میشه خط قبلی بالا میره و بعدی از پایین می‌آد؛ جرقه هم هر بار یک‌چهارم دور می‌چرخه.",
    usage: `import { ThinkingStates } from "@/components/animations/thinking-states"\n\n<ThinkingStates states={["در حال خواندن فایل‌ها", "در حال اجرای دستور", "در حال نوشتن پاسخ"]} />`,
    props: [
      { name: "states", type: "string[]", desc: "حالت‌ها به ترتیب." },
      { name: "hold", type: "number", default: "2000", desc: "میلی‌ثانیه ماندن هر حالت." },
      { name: "loop", type: "boolean", default: "true", desc: "بعد از آخری برگرده اول." },
      { name: "icon", type: "boolean", default: "true", desc: "آیکون جرقه‌ی چرخان." },
    ],
    promptBullets: ["Text uses background-clip:text with a moving 250% gradient (shimmer keyframes) while it holds.", "Swap is the text-swap motion: the outgoing line plays swap-out (translateY(-6px) + blur(2px) + fade) while the new one plays swap-in from +6px, both 150ms, in one grid cell.", "Width is reserved by an invisible copy of the longest state; role=status; the sparkle icon rotates index * 90deg with a 500ms ease."],
  },
  {
    slug: "reasoning-stream", name: "جریان استدلال", file: an("reasoning-stream"),
    desc: "کارتی که استدلال عامل را پخش می‌کنه: متن هر بار دو خط بالا میره، مکث می‌کنه و بدون پرش دوباره از اول شروع میشه. با هاور می‌ایسته.",
    usage: `import { ReasoningStream } from "@/components/animations/reasoning-stream"\n\n<ReasoningStream text={["اول فایل تنظیمات را می‌خوانم…", "به نظر می‌رسد مسیر خروجی اشتباه است."]} />`,
    props: [
      { name: "text", type: "string | string[]", desc: "متن یا پاراگراف‌ها." },
      { name: "lines", type: "number", default: "2", desc: "تعداد خط در هر قدم." },
      { name: "hold", type: "number", default: "1200", desc: "میلی‌ثانیه مکث بین قدم‌ها." },
      { name: "height", type: "number", default: "104", desc: "ارتفاع کارت به پیکسل." },
    ],
    promptBullets: ["Clone the transcript once inside the scroller; every `hold` ms tween translateY by lineHeight * lines with a 500ms cubic-bezier(0.22,1,0.36,1); when the offset passes one copy's height, subtract it with transition:none and a forced reflow so the loop never shows a jump.", "Top and bottom fades are a mask-image on the viewport, not painted gradients.", "Pause via a ref flag on hover; clean up timers and reset the transform on unmount."],
  },
  {
    slug: "streaming-text", name: "متن جریانی", file: an("streaming-text"), css: KF.pulse, wide: true,
    desc: "کلمه‌ها یکی‌یکی از دل تاری در می‌آن، انگار جواب مدل دارد شکل می‌گیره نه تایپ میشه؛ یک نقطه‌ی نرم هم تا رسیدن کلمه‌ی آخر سرِ جریان را نشان میده.",
    usage: `import { StreamingText } from "@/components/animations/streaming-text"\n\n<StreamingText text="پاسخ مدل این‌جا کلمه‌به‌کلمه ظاهر می‌شود." gap={60} />`,
    props: [
      { name: "text", type: "string", desc: "متن کامل." },
      { name: "gap", type: "number", default: "60", desc: "میلی‌ثانیه بین کلمه‌ها." },
      { name: "fade", type: "number", default: "300", desc: "میلی‌ثانیه‌ی رفع تاری هر کلمه." },
    ],
    notes: ["برای تایپ حرف‌به‌حرف از «تایپ‌شونده» استفاده کنید؛ این یکی برای حس جریان پاسخ مدله و چون کلمه‌ها جدا هستن اتصال حروف فارسی مشکلی نداره."],
    promptBullets: ["Split on whitespace into one span per word (never per character in Persian); the nth span turns opacity 1 / blur 0 after n * gap ms via a single setInterval with cleanup.", "Each word transitions opacity + filter over `fade` ms ease-out; the full text is exposed through aria-label and spans are aria-hidden.", "A 8px pulsing dot after the last resolved word fades out once every word is in."],
  },
  {
    slug: "matrix-loader", name: "لودر ماتریسی", file: an("matrix-loader"), css: KF.matrix,
    desc: "لودر ریز ۴×۴ که به جای چرخیدن، آروم می‌تپه؛ پنج الگو دارد و scan مثل خواندن از راست به چپ می‌ره.",
    usage: `import { MatrixLoader } from "@/components/animations/matrix-loader"\n\n<MatrixLoader variant="scan" />\n<MatrixLoader variant="orbit" rounded dot={4} />`,
    props: [
      { name: "variant", type: '"scan" | "twinkle" | "orbit" | "pulse" | "wave"', default: '"scan"', desc: "الگوی حرکت؛ فقط جدول تأخیرها فرق می‌کنه." },
      { name: "rounded", type: "boolean", default: "false", desc: "چهار گوشه حذف بشن." },
      { name: "dot", type: "number", default: "3", desc: "اندازه‌ی نقطه و فاصله به پیکسل." },
      { name: "cycle", type: "number", default: "1200", desc: "میلی‌ثانیه‌ی یک دور کامل." },
    ],
    promptBullets: ["16 <i> dots in an inline-grid with dir=ltr so column indices are physical; one matrix-pulse keyframe (25% foreground → foreground at 15%) with a per-dot animation-delay from a table.", "scan: (3 - col) * cycle/10 so it sweeps right to left; twinkle: a fixed shuffled order * cycle/16; orbit: the 8-cell ring * cycle/8 with a static centre; pulse: inner 4 first, others cycle*0.16 later; wave: (3 - col + row) * cycle/12 diagonal from the top-right.", "role=status with a Persian aria-label; rounded hides the four corners."],
  },
  {
    slug: "banner-stack", name: "پشته‌ی اعلان", file: an("banner-stack"), css: KF.bannerIn, wide: true,
    desc: "اعلان‌ها مثل یک دسته کارت روی هم می‌شینن: تازه‌ترین با کمی تاری بالا می‌آد، قدیمی‌ها کوچک‌تر و کم‌رنگ‌تر عقب می‌رن و با هاور همه باز میشن تا خوانده بشن.",
    usage: `import { BannerStack } from "@/components/animations/banner-stack"\n\nconst [items, setItems] = useState([])\nconst push = (b) => setItems((s) => [{ id: Date.now(), ...b }, ...s].slice(0, 5))\n<BannerStack items={items} />`,
    props: [
      { name: "items", type: "{ id; title; description?; icon? }[]", desc: "تازه‌ترین اول. فقط یکی بیشتر از max از ابتدای فهرست رندر میشه." },
      { name: "max", type: "number", default: "3", desc: "چند تا در پشته بمونن؛ بعدی محو میشه." },
    ],
    notes: ["برای toast معمولی از کامپوننت Toast استفاده کنید؛ این یکی را وقتی بردارید که اعلان‌ها ممکنه روی هم بیفتن و می‌خواید صف پشت سر جدیدترین دیده بشه."],
    promptBullets: ["All banners absolute at the bottom of a one-banner-tall box; depth d gets translateY(-10px * d) scale(1 - 0.05d) opacity(1 - 0.28d) blur(0.6px * d); depth ≥ max is the leaving pose (opacity 0).", "The depth-0 banner (keyed by id) plays a banner-in keyframe from translateY(16px) scale(0.96) blur(2px) opacity 0; since it lands on the identity pose nothing jumps and no pre-open state is needed.", "Hover (tracked on the container, with an invisible hit area covering the fanned height) spreads depth d to translateY(-d * (100% + 8px)) at full opacity.", "350ms cubic-bezier(0.22,1,0.36,1); aria-hidden on banners behind the front one while collapsed."],
  },
];
