import type { AnimationDoc } from "./types";

const an = (slug: string) => `registry/animations/${slug}.tsx`;

const KF = {
  shimmer: `@keyframes shimmer {\n  from { background-position: 200% center; }\n  to { background-position: -200% center; }\n}`,
  blurIn: `@keyframes blur-in {\n  from { opacity: 0; filter: blur(10px); transform: translateY(6px); }\n  to { opacity: 1; filter: blur(0); transform: translateY(0); }\n}`,
  slideIn: `@keyframes slide-in {\n  from { opacity: 0; transform: translateX(-14px); }\n  to { opacity: 1; transform: translateX(0); }\n}`,
  beam: `@property --beam-angle {\n  syntax: "<angle>";\n  inherits: false;\n  initial-value: 0deg;\n}\n@keyframes beam { to { --beam-angle: 360deg; } }`,
  shine: `@keyframes shine {\n  0% { transform: translateX(-120%) skewX(-15deg); }\n  60%, 100% { transform: translateX(220%) skewX(-15deg); }\n}`,
  orbit: `@keyframes orbit {\n  from { transform: rotate(0deg) translateX(var(--orbit-r, 44px)) rotate(0deg); }\n  to { transform: rotate(360deg) translateX(var(--orbit-r, 44px)) rotate(-360deg); }\n}`,
  bounce: `@keyframes bounce-dot {\n  0%, 80%, 100% { transform: translateY(0); opacity: 0.4; }\n  40% { transform: translateY(-6px); opacity: 1; }\n}`,
  marquee: `@keyframes marquee {\n  from { transform: translateX(-50%); }\n  to { transform: translateX(0); }\n}`,
  pulse: `@keyframes pulse-soft {\n  0%, 100% { opacity: 0.55; }\n  50% { opacity: 1; }\n}`,
  wordIn: `@keyframes word-in {\n  from { opacity: 0; transform: translateY(0.6em); filter: blur(4px); }\n  to { opacity: 1; transform: translateY(0); filter: blur(0); }\n}`,
  ripple: `@keyframes ripple {\n  from { transform: translate(-50%, -50%) scale(0); opacity: 0.35; }\n  to { transform: translate(-50%, -50%) scale(4); opacity: 0; }\n}`,
  check: `@keyframes pop {\n  0% { transform: scale(0.6); opacity: 0; }\n  60% { transform: scale(1.08); opacity: 1; }\n  100% { transform: scale(1); }\n}\n@keyframes draw { to { stroke-dashoffset: 0; } }\n@keyframes word-in {\n  from { opacity: 0; transform: translateY(0.6em); filter: blur(4px); }\n  to { opacity: 1; transform: translateY(0); filter: blur(0); }\n}`,
  meteor: `@keyframes meteor {\n  0% { transform: rotate(215deg) translateX(0); opacity: 1; }\n  70% { opacity: 1; }\n  100% { transform: rotate(215deg) translateX(-420px); opacity: 0; }\n}`,
  tileIn: `@keyframes tile-in {\n  from { opacity: 0; transform: scale(0.7); }\n  to { opacity: 1; transform: scale(1); }\n}`,
  wipeIn: `@keyframes wipe-in {\n  from { clip-path: inset(0 0 0 100%); transform: translateY(0.35em); opacity: 0; }\n  to { clip-path: inset(0 0 0 0); transform: translateY(0); opacity: 1; }\n}`,
  gradientPan: `@keyframes gradient-pan {\n  from { background-position: 0% 50%; }\n  to { background-position: 150% 50%; }\n}`,
  beamTravel: `@keyframes beam-travel {\n  from { stroke-dashoffset: 28; }\n  to { stroke-dashoffset: -100; }\n}`,
  confetti: `@keyframes confetti {\n  0% { transform: translate(-50%, 0) rotate(0deg); opacity: 1; }\n  60% { transform: translate(calc(-50% + var(--cx)), var(--cy)) rotate(calc(var(--cr) * 0.6)); opacity: 1; }\n  100% { transform: translate(calc(-50% + var(--cx) * 1.3), 40px) rotate(var(--cr)); opacity: 0; }\n}`,
  sparkle: `@keyframes sparkle {\n  0%, 100% { opacity: 0; transform: scale(0) rotate(0deg); }\n  50% { opacity: 1; transform: scale(1) rotate(90deg); }\n}`,
  pulseRing: `@keyframes pulse-ring {\n  0% { transform: scale(1); opacity: 0.6; }\n  100% { transform: scale(1.4); opacity: 0; }\n}`,
};

export const animations: AnimationDoc[] = [
  {
    slug: "text-shimmer", name: "متن درخشان", file: an("text-shimmer"), css: KF.shimmer,
    desc: "نور از روی متن می‌گذرد؛ برای حالت «در حال فکر کردن».",
    usage: `import { TextShimmer } from "@/components/animations/text-shimmer"\n\n<TextShimmer className="text-lg font-semibold">در حال فکر کردن…</TextShimmer>`,
    props: [{ name: "duration", type: "number", default: "3", desc: "ثانیه برای هر دور." }],
    promptBullets: ["Horizontal gradient from muted-foreground to foreground with background-clip:text and moving background-position.", "Text must stay selectable and readable; only the color animates."],
  },
  {
    slug: "typewriter", name: "تایپ‌شونده", file: an("typewriter"), css: KF.pulse,
    desc: "متن حرف‌به‌حرف ظاهر می‌شود؛ اتصال حروف فارسی درست می‌ماند.",
    usage: `import { Typewriter } from "@/components/animations/typewriter"\n\n<Typewriter text="یک فرم ثبت‌نام فارسی بساز." speed={70} loopDelay={2000} />`,
    props: [
      { name: "speed", type: "number", default: "70", desc: "میلی‌ثانیه برای هر حرف." },
      { name: "loopDelay", type: "number", default: "0", desc: "مکث در پایان و شروع دوباره؛ صفر یعنی یک بار." },
    ],
    notes: ["چون هر بار زیررشته‌ی کامل رندر می‌شود، حروف فارسی درست به هم می‌چسبند؛ حرف‌ها را جدا انیمیت نکنید."],
    promptBullets: ["Render text.slice(0, n), not separate letters, so Persian glyph joining stays intact.", "Cursor is a pulsing vertical bar after the text; aria-label is the full string."],
  },
  {
    slug: "counter", name: "شمارنده", file: an("counter"), wide: true,
    desc: "وقتی وارد دید شد، عدد تا مقدار نهایی می‌رسد؛ با ارقام فارسی.",
    usage: `import { Counter } from "@/components/animations/counter"\n\n<Counter to={12_450_000} unit="تومان" className="text-3xl font-bold" />`,
    props: [
      { name: "to / from", type: "number", desc: "مقصد و شروع." },
      { name: "duration", type: "number", default: "1600", desc: "میلی‌ثانیه." },
      { name: "format", type: "(n) => string", default: "faNumber", desc: "قالب خودِ عدد." },
      { name: "unit", type: "ReactNode", desc: "واحد، بیرون از جعبه‌ی عدد تا هیچ‌وقت جابه‌جا نشود." },
    ],
    notes: ["مقدار نهایی نامرئی زیر عدد رندر می‌شود تا عرض از اول رزرو شود. واحد بیرون از آن جعبه است؛ وقتی تعداد رقم‌ها عوض می‌شود (مثلاً عبور از ۱۰ میلیون) نه عدد می‌پرد نه «تومان»."],
    promptBullets: ["Start with IntersectionObserver when it enters view; ease-out cubic easing.", "requestAnimationFrame with cleanup on unmount.", "Reserve width with an invisible copy of the final value, overlay the animated number absolute and RTL (anchor on the ones digit), and render the unit outside that box so digit-count changes do not jiggle."],
  },
  {
    slug: "blur-text", name: "ظهور تار", file: an("blur-text"), css: KF.blurIn,
    desc: "کلمه‌ها از تاری بیرون می‌آیند، از راست به چپ.",
    usage: `import { BlurText } from "@/components/animations/blur-text"\n\n<h1 className="text-4xl font-bold"><BlurText text="کامپوننت‌هایی که فارسی را می‌فهمند" /></h1>`,
    props: [{ name: "delay", type: "number", default: "120", desc: "فاصله‌ی شروع هر کلمه (میلی‌ثانیه)." }],
    promptBullets: ["Each word is an inline-block span with an increasing animation-delay; keep gaps with &nbsp;.", "Because the document is rtl, natural word order is already right-to-left; do not reverse it."],
  },
  {
    slug: "animated-tabs", name: "تب‌های لغزان", file: an("animated-tabs"),
    desc: "نشانگر زیر تب فعال سُر می‌خورد.",
    usage: `import { AnimatedTabs } from "@/components/animations/animated-tabs"\n\n<AnimatedTabs items={["همه", "فعال", "بایگانی"]} onChange={setTab} />`,
    props: [{ name: "items", type: "string[]", desc: "برچسب تب‌ها." }, { name: "value / onChange", type: "number", desc: "شاخص تب فعال." }],
    promptBullets: ["Indicator uses inset-inline-start with a transition on that property; width calc((100% - padding) / n).", "No getBoundingClientRect measurement."],
  },
  {
    slug: "border-beam", name: "حاشیه‌ی نورانی", file: an("border-beam"), css: KF.beam,
    desc: "پرتو نور دور کارت می‌چرخد.",
    usage: `import { BorderBeam } from "@/components/animations/border-beam"\n\n<BorderBeam><div className="p-4">پلن حرفه‌ای</div></BorderBeam>`,
    props: [{ name: "duration", type: "number", default: "4", desc: "ثانیه برای یک دور." }, { name: "color", type: "string", default: "var(--foreground)", desc: "رنگ پرتو." }],
    promptBullets: ["conic-gradient with a --beam-angle variable registered via @property so it can animate.", "Gradient layer inset-[-100%] behind the card with 1px padding so only the border shows."]
  },
  {
    slug: "shine-button", name: "دکمه‌ی درخشان", file: an("shine-button"), css: KF.shine, registryDeps: ["button"],
    desc: "نوار نور روی دکمه؛ برای عمل اصلی صفحه.",
    usage: `import { ShineButton } from "@/components/animations/shine-button"\n\n<ShineButton><Sparkles />ارتقا به پرو</ShineButton>`,
    promptBullets: ["An absolute span with a skewed gradient that sweeps right-to-left every 2s; pointer-events-none.", "Use on the page's primary button only, one instance."],
  },
  {
    slug: "dock", name: "داک", file: an("dock"), wide: true,
    desc: "آیکون‌ها با نزدیک‌شدن ماوس بزرگ می‌شوند.",
    usage: `import { Dock } from "@/components/animations/dock"\n\n<Dock items={[{ icon: Home, label: "خانه" }, { icon: Search, label: "جست‌وجو" }]} />`,
    props: [{ name: "items", type: "{ icon; label; onClick? }[]", desc: "آیکون‌ها با برچسب برای aria." }],
    promptBullets: ["CSS only: hover:scale-[1.4] on the item; container h-20 with items-end so the grown icon stays in frame, neighbors scale a bit via :has(+ :hover) and :hover + &.", "origin-bottom so they grow from the bottom; role=toolbar."],
  },
  {
    slug: "animated-list", name: "فهرست متحرک", file: an("animated-list"), css: KF.slideIn,
    desc: "آیتم‌ها یکی‌یکی از راست وارد می‌شوند؛ مناسب اعلان‌ها.",
    usage: `import { AnimatedList } from "@/components/animations/animated-list"\n\n<AnimatedList stagger={200}>\n  <NotificationRow … />\n  <NotificationRow … />\n</AnimatedList>`,
    props: [{ name: "stagger", type: "number", default: "200", desc: "فاصله‌ی ورود آیتم‌ها (میلی‌ثانیه)." }],
    promptBullets: ["Each child in an li with animation-delay = index × stagger; enter from the right (negative translateX).", "animation-fill-mode: both so they stay hidden until their turn."],
  },
  {
    slug: "orbit", name: "مدار", file: an("orbit"), css: KF.orbit,
    desc: "عناصر دور یک مرکز می‌چرخند و همیشه رو به بالا می‌مانند.",
    usage: `import { Orbit } from "@/components/animations/orbit"\n\n<Orbit center={<Logo />} items={[{ node: <Icon />, radius: 64, duration: 9 }, { node: <Icon />, radius: 44, duration: 6 }]} />`,
    props: [{ name: "items", type: "{ node; radius; duration?; delay? }[]", desc: "هر آیتم مدار خودش را دارد." }, { name: "size", type: "number", default: "160", desc: "قطر ظرف." }],
    promptBullets: ["Keyframe: rotate(a) translateX(r) rotate(-a) so the item does not spin; radius via --orbit-r.", "Dashed rings for each unique radius."],
  },
  {
    slug: "tilt-card", name: "کارت سه‌بعدی", file: an("tilt-card"),
    desc: "کارت با حرکت ماوس کج می‌شود.",
    usage: `import { TiltCard } from "@/components/animations/tilt-card"\n\n<TiltCard className="p-4">…</TiltCard>`,
    props: [{ name: "max", type: "number", default: "14", desc: "حداکثر زاویه به درجه." }],
    promptBullets: ["perspective(600px) rotateX/rotateY from relative mouse position (−0.5 to 0.5); reset to zero on mouseleave.", "Short 150ms transition so motion is smooth but responsive."],
  },
  {
    slug: "loading-dots", name: "نقاط بارگذاری", file: an("loading-dots"), css: KF.bounce,
    desc: "سه نقطه‌ی ضربان‌دار برای انتظار کوتاه.",
    usage: `import { LoadingDots } from "@/components/animations/loading-dots"\n\n<LoadingDots label="در حال دریافت پاسخ" />`,
    promptBullets: ["Three dots with animation-delay 0, 160, and 320ms; role=status and a text label beside them."],
  },
  {
    slug: "marquee", name: "نوار متحرک", file: an("marquee"), css: KF.marquee,
    desc: "حرکت پیوسته از چپ به راست، جهت طبیعی فارسی.",
    usage: `import { Marquee } from "@/components/animations/marquee"\n\n<Marquee duration={20}>\n  {tags.map((t) => <Badge key={t}>{t}</Badge>)}\n</Marquee>`,
    props: [{ name: "duration", type: "number", default: "30", desc: "ثانیه برای یک دور." }, { name: "gap", type: "string", default: '"1rem"', desc: "فاصله‌ی آیتم‌ها." }],
    promptBullets: ["Render the content twice and animate the container from translateX(-50%) to 0 for a seamless left-to-right loop.", "Outer container dir=ltr for transform math, inner content dir=rtl; fade both edges with mask-image."],
  },
  {
    slug: "reveal", name: "ظهور هنگام اسکرول", file: an("reveal"),
    desc: "بخش‌ها وقتی وارد دید می‌شوند بالا می‌آیند؛ فقط یک بار.",
    usage: `import { Reveal } from "@/components/animations/reveal"\n\n<Reveal delay={100}><FeatureCard /></Reveal>`,
    props: [{ name: "delay", type: "number", default: "0", desc: "تأخیر شروع (میلی‌ثانیه)." }],
    promptBullets: ["IntersectionObserver with a negative bottom rootMargin so it starts a bit late; disconnect after first entry.", "Transition opacity and transform; if IntersectionObserver is missing, show immediately."],
  },
  {
    slug: "word-rotate", name: "چرخش کلمه", file: an("word-rotate"), css: KF.wordIn,
    desc: "یک جای جمله بین چند کلمه می‌چرخد؛ هر کلمه با تاری نرم بالا می‌آید.",
    usage: `import { WordRotate } from "@/components/animations/word-rotate"\n\n<h1>کامپوننت‌های فارسی، برای <WordRotate words={["توسعه‌دهنده", "طراح", "وایب‌کدر"]} /></h1>`,
    props: [{ name: "words", type: "string[]", desc: "کلمه‌ها به ترتیب." }, { name: "interval", type: "number", default: "2200", desc: "میلی‌ثانیه برای هر کلمه." }],
    promptBullets: ["inline-grid container with an invisible copy of the longest word so width stays fixed and the sentence does not jump.", "Render the new word with a fresh key so the CSS animation restarts; aria-live=polite."],
  },
  {
    slug: "text-scramble", name: "رمزگشایی متن", file: an("text-scramble"),
    desc: "حرف‌ها بین حروف تصادفی فارسی می‌چرخند و از ابتدای جمله یکی‌یکی ثابت می‌شوند.",
    usage: `import { TextScramble } from "@/components/animations/text-scramble"\n\n<TextScramble text="کامپوننت‌هایی که فارسی را می‌فهمند" className="text-xl font-bold" />`,
    props: [{ name: "speed", type: "number", default: "40", desc: "میلی‌ثانیه برای هر فریم." }],
    promptBullets: ["Letter pool is Persian letters only (not Latin) so the word shape stays Persian; spaces and ZWNJ stay untouched.", "Resolve from the start of the string (the right in RTL); full text in aria-label."],
  },
  {
    slug: "odometer", name: "شماره‌انداز", file: an("odometer"), wide: true,
    desc: "هر رقم مثل کنتور مکانیکی به مقدار جدید می‌غلتد؛ برای قیمت‌های زنده.",
    usage: `import { Odometer } from "@/components/animations/odometer"\n\n<Odometer value={price} unit="تومان" className="text-3xl font-bold" />`,
    props: [{ name: "value", type: "number", desc: "مقدار؛ با هر تغییر رقم‌ها می‌غلتند." }, { name: "unit", type: "string", desc: "واحد کوچک کنار عدد." }],
    promptBullets: ["Each digit is a 1em-tall overflow-hidden column with a 0–9 strip inside, moved by translateY(-n em).", "Digits inside the number are dir=ltr; thousands separator «٬» is static; ~700ms transition."],
  },
  {
    slug: "ripple-button", name: "دکمه‌ی موجی", file: an("ripple-button"), css: KF.ripple, registryDeps: ["button"],
    desc: "از نقطه‌ی لمس یک موج بیرون می‌زند؛ بازخورد لمسی برای موبایل.",
    usage: `import { RippleButton } from "@/components/animations/ripple-button"\n\n<RippleButton>پرداخت</RippleButton>`,
    promptBullets: ["On click, take relative click coords and add a round span there with a scale animation; remove it after 650ms.", "Button overflow-hidden; text z-index above the ripple."],
  },
  {
    slug: "magnetic-button", name: "دکمه‌ی آهنربایی", file: an("magnetic-button"), registryDeps: ["button"],
    desc: "وقتی ماوس نزدیک می‌شود دکمه کمی به سمتش کشیده می‌شود.",
    usage: `import { MagneticButton } from "@/components/animations/magnetic-button"\n\n<MagneticButton strength={10}>شروع کنید</MagneticButton>`,
    props: [{ name: "strength", type: "number", default: "10", desc: "حداکثر جابه‌جایی به پیکسل." }],
    promptBullets: ["Hit area larger than the button (padding) so reaction starts before the pointer arrives; reset to zero on mouseleave.", "Short ease-out transition; inert on touch and that is fine."],
  },
  {
    slug: "progress-ring", name: "حلقه‌ی پیشرفت", file: an("progress-ring"),
    desc: "حلقه‌ی SVG که با ورود به دید پر می‌شود؛ درصد فارسی وسط آن.",
    usage: `import { ProgressRing } from "@/components/animations/progress-ring"\n\n<ProgressRing value={72} label="هدف ماهانه" />`,
    props: [{ name: "value", type: "number", desc: "درصد ۰ تا ۱۰۰." }, { name: "size / stroke", type: "number", default: "96 / 8", desc: "قطر و ضخامت." }],
    promptBullets: ["Two SVG circles; the second has stroke-dasharray equal to circumference and stroke-dashoffset mapped to percent, with a transition.", "svg with -rotate-90 so it starts at the top; role=progressbar and percent with Persian «٪»."],
  },
  {
    slug: "success-check", name: "تیک موفقیت", file: an("success-check"), css: KF.check,
    desc: "دایره جهش می‌کند و تیک خودش را می‌کشد؛ برای پایان پرداخت و ثبت‌نام.",
    usage: `import { SuccessCheck } from "@/components/animations/success-check"\n\n<SuccessCheck label="پرداخت انجام شد" />`,
    promptBullets: ["Check path with stroke-dasharray equal to its length and stroke-dashoffset from that value to zero (draw-on).", "Circle pops with a little overshoot; label appears after the check with a delay."],
  },
  {
    slug: "meteors", name: "بارش شهاب", file: an("meteors"), css: KF.meteor,
    desc: "رگه‌های نور از بالا-راست به پایین-چپ می‌ریزند؛ برای هیرو و کارت‌های ویژه.",
    usage: `import { Meteors } from "@/components/animations/meteors"\n\n<div className="relative overflow-hidden rounded-xl border p-8">\n  <Meteors count={12} />\n  …\n</div>`,
    props: [{ name: "count", type: "number", default: "12", desc: "تعداد شهاب." }],
    promptBullets: ["Each meteor is a 1px gradient line with a bright head; rotate(215deg) and negative translateX so they fall right to left.", "Delay and duration are pseudo-random from the index so they stay stable across renders (no Math.random)."],
  },
  {
    slug: "spotlight-card", name: "کارت نورانی", file: an("spotlight-card"),
    desc: "یک هاله‌ی نرم دنبال ماوس روی کارت حرکت می‌کند و حاشیه را روشن می‌کند.",
    usage: `import { SpotlightCard } from "@/components/animations/spotlight-card"\n\n<SpotlightCard><div className="p-5">…</div></SpotlightCard>`,
    promptBullets: ["Absolute layer with a radial-gradient at mouse coords; card has 1px padding so the glow shows on the border too.", "On mouseleave move the coords outside the card so it fades."],
  },
  {
    slug: "grid-reveal", name: "ظهور شبکه‌ای", file: an("grid-reveal"), css: KF.tileIn,
    desc: "کاشی‌ها به‌صورت موج قطری از بالا-راست ظاهر می‌شوند.",
    usage: `import { GridReveal } from "@/components/animations/grid-reveal"\n\n<GridReveal cols={6} rows={3} />`,
    props: [{ name: "cols / rows", type: "number", default: "6 / 3", desc: "ابعاد شبکه." }, { name: "step", type: "number", default: "60", desc: "فاصله‌ی زمانی هر قطر." }],
    promptBullets: ["Each tile's delay = (row + col) × step; because column 0 is the right in RTL, the wave starts top-right.", "animation-fill-mode: both so tiles stay hidden until their turn."],
  },
  {
    slug: "text-reveal", name: "ظهور ماسکی", file: an("text-reveal"), css: KF.wipeIn, wide: true,
    desc: "هر خط تیتر از پشت یک ماسک، از راست بیرون می‌آید؛ خط‌ها پشت سر هم.",
    usage: `import { TextReveal } from "@/components/animations/text-reveal"\n\n<h1 className="text-4xl font-bold"><TextReveal lines={["زیرساخت پرداخت", "برای محصول دیجیتال شما"]} /></h1>`,
    props: [{ name: "lines", type: "string[]", desc: "هر عضو یک خط است." }, { name: "stagger", type: "number", default: "140", desc: "فاصله‌ی شروع خط‌ها (میلی‌ثانیه)." }, { name: "duration", type: "number", default: "900", desc: "مدت هر خط (میلی‌ثانیه)." }],
    notes: ["ماسک با clip-path است نه overflow؛ برای همین دنباله‌ی حروفی مثل «ی» و «ج» بریده نمی‌شود."],
    promptBullets: ["Each line is a block span animating clip-path from inset(0 0 0 100%) to inset(0) so it uncovers from the right; add a small translateY.", "Delay = index × stagger; animation-fill-mode both; the full text goes in aria-label and the lines are aria-hidden."],
  },
  {
    slug: "highlight-text", name: "هایلایت متن", file: an("highlight-text"),
    desc: "یک خط ماژیک زیر عبارت کشیده می‌شود، از راست، وقتی وارد دید شد.",
    usage: `import { HighlightText } from "@/components/animations/highlight-text"\n\n<h2>قیمت‌ها <HighlightText>ساده و شفاف</HighlightText> هستند</h2>`,
    props: [{ name: "delay", type: "number", default: "0", desc: "تأخیر شروع (میلی‌ثانیه)." }],
    promptBullets: ["A linear-gradient background with background-size animating from 0% to 100% width and a fixed 0.5em height; background-position 100% 100% so it grows from the right.", "Trigger with IntersectionObserver at 0.6 threshold, once; box-decoration-break: clone for phrases that wrap."],
  },
  {
    slug: "gradient-text", name: "متن گرادیانی", file: an("gradient-text"), css: KF.gradientPan,
    desc: "گرادیان رنگ برند آرام روی متن حرکت می‌کند؛ متن انتخاب‌شدنی می‌ماند.",
    usage: `import { GradientText } from "@/components/animations/gradient-text"\n\n<h1 className="text-4xl font-bold"><GradientText>به‌زودی راه می‌افتیم</GradientText></h1>`,
    props: [{ name: "duration", type: "number", default: "6", desc: "ثانیه برای یک دور کامل." }],
    promptBullets: ["Five-stop gradient foreground→brand→foreground→brand→foreground at background-size 300% with background-clip:text; animate background-position from 0% to 150% for a seamless loop.", "Only the fill animates; no letter-spacing, no transform on the text."],
  },
  {
    slug: "flip-card", name: "کارت برگردان", file: an("flip-card"),
    desc: "کارت با هاور یا کلیک دور محور عمودی می‌چرخد و پشتش را نشان می‌دهد.",
    usage: `import { FlipCard } from "@/components/animations/flip-card"\n\n<FlipCard front={<div className="p-4">قیمت پلن</div>} back={<div className="p-4">۲۹۰٬۰۰۰ تومان / ماه</div>} />`,
    props: [{ name: "front / back", type: "ReactNode", desc: "دو رو؛ اندازه از روی رو گرفته می‌شود." }, { name: "trigger", type: '"hover" | "click"', default: '"hover"', desc: "با کلیک، کارت نقش دکمه می‌گیرد و با Enter هم برمی‌گردد." }],
    promptBullets: ["Outer perspective:1200px; inner transform-style:preserve-3d with a 700ms rotateY(180deg) transition on hover/focus-within (or a click state).", "Both faces backface-visibility:hidden; the back is absolute inset-0 pre-rotated 180deg; click mode gets role=button, tabIndex 0 and aria-pressed."],
  },
  {
    slug: "animated-beam", name: "پرتو اتصال", file: an("animated-beam"), css: KF.beamTravel, wide: true,
    desc: "بین دو عنصر یک منحنی می‌کشد و نبض نور روی آن می‌فرستد؛ برای نمایش یکپارچه‌سازی‌ها.",
    usage: `import { AnimatedBeam } from "@/components/animations/animated-beam"\n\nconst box = useRef(null), a = useRef(null), b = useRef(null)\n\n<div ref={box} className="relative">\n  <div ref={a}>…</div><div ref={b}>…</div>\n  <AnimatedBeam containerRef={box} fromRef={a} toRef={b} curvature={-40} />\n</div>`,
    props: [{ name: "containerRef / fromRef / toRef", type: "RefObject", desc: "ظرف relative و دو انتها." }, { name: "curvature", type: "number", default: "0", desc: "خمیدگی به پیکسل؛ مثبت رو به پایین." }, { name: "duration / delay", type: "number", default: "4 / 0", desc: "ثانیه." }, { name: "reverse", type: "boolean", default: "false", desc: "نور از مقصد به مبدأ." }],
    notes: ["با pathLength=100 محاسبه‌ی dash از طول واقعی مسیر مستقل است؛ نیازی به getTotalLength نیست.", "خط با z-index منفی زیر دو سر می‌نشیند؛ به ظرف relative isolate بدهید تا پشت پس‌زمینه‌ی ظرف نرود."],
    promptBullets: ["Measure the two ends relative to the container with getBoundingClientRect and draw a quadratic path; re-measure with ResizeObserver.", "SVG is absolute inset-0 with a negative z-index inside a relative isolate container so the line passes behind the endpoints. Three stacked paths: a faint base line, a wide low-opacity glow and a 2px brand stroke; the last two use pathLength=100, stroke-dasharray 28 100 and animate stroke-dashoffset 28 → -100; reverse via animation-direction."],
  },
  {
    slug: "confetti", name: "کاغذ رنگی", file: an("confetti"), css: KF.confetti,
    desc: "انفجار کاغذرنگی از پایین وسط؛ برای پایان پرداخت و ثبت‌نام.",
    usage: `import { Confetti } from "@/components/animations/confetti"\n\n<div className="relative overflow-hidden">\n  {paid && <Confetti key={paidAt} />}\n  …\n</div>`,
    props: [{ name: "count", type: "number", default: "60", desc: "تعداد تکه‌ها." }],
    notes: ["یک‌بار اجرا می‌شود؛ برای تکرار، key را عوض کنید تا دوباره mount شود."],
    promptBullets: ["Each piece is a small span at bottom-center with per-piece CSS variables --cx, --cy, --cr set from a deterministic hash of the index (no Math.random) so SSR and client match.", "Keyframes rise to (--cx, --cy) at 60% then fall below the origin while fading; colors only from theme tokens (brand, foreground, success, warning, destructive)."],
  },
  {
    slug: "swipe-to-confirm", name: "کشیدن برای تأیید", file: an("swipe-to-confirm"), wide: true,
    desc: "دستگیره را از راست به چپ بکشید تا پرداخت تأیید شود؛ اگر زود رها کنید برمی‌گردد.",
    usage: `import { SwipeToConfirm } from "@/components/animations/swipe-to-confirm"\n\n<SwipeToConfirm label="برای پرداخت بکشید" doneLabel="پرداخت انجام شد" onConfirm={pay} />`,
    props: [{ name: "label / doneLabel", type: "string", desc: "متن قبل و بعد از تأیید." }, { name: "onConfirm", type: "() => void", desc: "وقتی دستگیره به انتها رسید." }],
    notes: ["برای کاربر کیبورد، Enter یا Space روی دستگیره مستقیم تأیید می‌کند؛ کشیدن اجباری نیست."],
    promptBullets: ["Pointer events with setPointerCapture; progress = (dx × direction) / (trackWidth − handle) where direction is −1 under rtl; release at ≥ 0.9 confirms, otherwise snap back with a transition.", "Position the handle with inset-inline-start (calc from progress) so it starts at the RTL start; label fades as progress grows; touch-none on the handle."],
  },
  {
    slug: "terminal", name: "ترمینال", file: an("terminal"), wide: true,
    desc: "دستورها حرف‌به‌حرف تایپ می‌شوند و خروجی زیرشان چاپ می‌شود؛ خروجی فارسی راست‌چین می‌ماند.",
    usage: `import { Terminal } from "@/components/animations/terminal"\n\n<Terminal lines={[\n  { type: "cmd", text: "npx vibefarsi add otp-field" },\n  { type: "ok", text: "otp-field به components/ui اضافه شد" },\n]} />`,
    props: [{ name: "lines", type: '{ type: "cmd" | "out" | "ok" | "err"; text }[]', desc: "به ترتیب اجرا." }, { name: "speed", type: "number", default: "45", desc: "میلی‌ثانیه برای هر حرف." }, { name: "title", type: "string", default: '"ترمینال"', desc: "عنوان نوار بالا." }],
    promptBullets: ["State: number of finished lines and typed characters of the current command; a single timeout advances one step (type a character, or print the next line).", "Command rows are dir=ltr with a $ prompt and a pulsing block cursor; output rows keep the document's rtl and colour by type (✓ success, ✗ destructive); start via IntersectionObserver."],
  },
  {
    slug: "card-stack", name: "پشته‌ی کارت", file: an("card-stack"),
    desc: "کارت‌ها روی هم؛ هر چند ثانیه کارت جلویی به ته صف می‌رود. مناسب نظرات مشتری.",
    usage: `import { CardStack } from "@/components/animations/card-stack"\n\n<CardStack className="h-44" items={reviews.map((r) => <Review key={r.id} {...r} />)} />`,
    props: [{ name: "items", type: "ReactNode[]", desc: "کارت‌ها به ترتیب اولیه." }, { name: "interval", type: "number", default: "3200", desc: "میلی‌ثانیه بین جابه‌جایی‌ها." }, { name: "offset / scale", type: "number", default: "12 / 0.05", desc: "جابه‌جایی و کوچک‌شدن هر لایه." }],
    promptBullets: ["Keep an order array and rotate it on an interval; each card is absolute inset-0 with transform translateY(depth × offset) scale(1 − depth × scale), origin top, and z-index by depth.", "Pause the interval on hover; cards deeper than two fade out; only the front card is not aria-hidden."],
  },
  {
    slug: "morph-button", name: "دکمه‌ی سه‌حالته", file: an("morph-button"),
    desc: "یک دکمه برای عادی → در حال انجام → انجام شد؛ حالت‌ها درجا محو می‌شوند و عرض نمی‌پرد.",
    usage: `import { MorphButton } from "@/components/animations/morph-button"\n\n<MorphButton onAction={() => subscribe(email)} loadingText="در حال ثبت…" doneText="ثبت شد">خبرم کن</MorphButton>`,
    props: [{ name: "onAction", type: "() => Promise<unknown> | void", desc: "تا resolve شود، حالت «در حال انجام» می‌ماند." }, { name: "loadingText / doneText", type: "string", desc: "متن دو حالت بعدی." }, { name: "resetAfter", type: "number", default: "2200", desc: "میلی‌ثانیه تا برگشت به حالت عادی؛ صفر یعنی هرگز." }],
    promptBullets: ["inline-grid button where all three states occupy the same cell (col-start-1 row-start-1) so the width is the widest state from the first render; inactive states are opacity 0, translateY 8px and pointer-events none.", "aria-live=polite and aria-busy while loading; disabled outside idle; background switches to success on done."],
  },
  {
    slug: "compare-slider", name: "مقایسه‌ی قبل و بعد", file: an("compare-slider"), wide: true,
    desc: "دو لایه با یک خط جداکننده‌ی کشیدنی؛ «قبل» سمت راست است و خط با کیبورد هم جابه‌جا می‌شود.",
    usage: `import { CompareSlider } from "@/components/animations/compare-slider"\n\n<CompareSlider before={<img src="/old.png" alt="" />} after={<img src="/new.png" alt="" />} />`,
    props: [{ name: "before / after", type: "ReactNode", desc: "دو لایه؛ اندازه از «قبل» گرفته می‌شود." }, { name: "beforeLabel / afterLabel", type: "string", default: '"قبل" / "بعد"', desc: "برچسب گوشه‌ها." }, { name: "defaultValue", type: "number", default: "50", desc: "درصد اولیه از سمت راست." }],
    promptBullets: ["The after layer is absolute and clipped with clip-path: inset(0 v% 0 0) so the divider sits v% from the right (the RTL start); the before layer is in normal flow and gives the box its size.", "The control is a full-size transparent <input type=range> (browsers mirror it under rtl), so dragging, clicking and arrow keys all work; aria-valuetext with Persian digits and «٪»."],
  },
  {
    slug: "scratch-card", name: "کارت خراشیدنی", file: an("scratch-card"),
    desc: "روکش را با انگشت یا ماوس بخراشید تا کد تخفیف زیرش پیدا شود؛ وقتی نصفش رفت خودش پاک می‌شود.",
    usage: `import { ScratchCard } from "@/components/animations/scratch-card"\n\n<ScratchCard coverText="بخراشید" onReveal={track}>\n  <div className="p-6 text-center">کد تخفیف: <b dir="ltr">NOWRUZ40</b></div>\n</ScratchCard>`,
    props: [{ name: "coverText", type: "string", default: '"اینجا را بخراشید"', desc: "متن روی روکش." }, { name: "brushSize", type: "number", default: "22", desc: "شعاع قلم به پیکسل." }, { name: "threshold", type: "number", default: "0.45", desc: "چه کسری پاک شود تا کامل باز شود." }],
    promptBullets: ["A canvas over the content, scaled by devicePixelRatio, painted with the --secondary token, diagonal stripes and the cover text (ctx.direction = rtl); pointer moves with buttons pressed erase circles using destination-out.", "Every ~10 moves sample alpha of every 8th pixel; past the threshold fade the canvas out and call onReveal; touch-none, role=button and Enter reveals for keyboard users."],
  },
  {
    slug: "sparkles", name: "جرقه", file: an("sparkles"), css: KF.sparkle,
    desc: "ستاره‌های ریز دور یک کلمه یا نشان چشمک می‌زنند؛ برای «جدید» و «ویژه».",
    usage: `import { Sparkles } from "@/components/animations/sparkles"\n\n<Sparkles><Badge variant="brand">جدید</Badge></Sparkles>`,
    props: [{ name: "count", type: "number", default: "7", desc: "تعداد جرقه‌ها." }],
    promptBullets: ["Inline-block relative wrapper; each sparkle is a tiny absolutely-positioned four-point star SVG in the brand colour, placed by a deterministic hash of its index (no Math.random).", "Keyframes scale 0 → 1 → 0 with a 90deg rotation and per-sparkle duration/delay so they never blink in sync."],
  },
  {
    slug: "scroll-progress", name: "پیشرفت خواندن", file: an("scroll-progress"), wide: true,
    desc: "نوار باریک بالای صفحه که با اسکرول از راست پر می‌شود؛ برای مقاله و مستندات.",
    usage: `import { ScrollProgress } from "@/components/animations/scroll-progress"\n\n// app/blog/[slug]/page.tsx\n<ScrollProgress />\n\n// or inside a scroll box\n<div ref={box} className="overflow-auto"><ScrollProgress targetRef={box} className="sticky" />…</div>`,
    props: [{ name: "targetRef", type: "RefObject<HTMLElement>", desc: "جعبه‌ی اسکرول‌شونده؛ بدون آن، خودِ صفحه." }],
    promptBullets: ["Listen to scroll (passive) on the target or window and set progress = scrollTop / (scrollHeight − clientHeight); transform: scaleX(progress) with transform-origin right so it grows from the RTL start.", "role=progressbar with aria-valuenow; fixed inset-x-0 top-0 by default, overridable via className."],
  },
  {
    slug: "pulse-button", name: "دکمه‌ی ضربان‌دار", file: an("pulse-button"), css: KF.pulseRing, registryDeps: ["button"],
    desc: "دو حلقه پشت دکمه باز می‌شوند تا عمل اصلی صفحه به چشم بیاید.",
    usage: `import { PulseButton } from "@/components/animations/pulse-button"\n\n<PulseButton size="lg">شروع رایگان</PulseButton>`,
    promptBullets: ["Wrap the Button in a relative span with two absolute inset-0 layers in primary/40 that animate scale 1 → 1.4 and opacity 0.6 → 0, offset by half the period.", "Layers copy the button's radius by size; one instance per page."],
  },
];
