import type { BackgroundDoc } from "./types";

const bg = (slug: string) => `registry/backgrounds/${slug}.tsx`;
const KF = {
  aurora: `@keyframes aurora {\n  0% { transform: translate(-10%, -10%) scale(1); }\n  50% { transform: translate(10%, 5%) scale(1.15); }\n  100% { transform: translate(-5%, 10%) scale(0.95); }\n}`,
  gridFlow: `@keyframes grid-flow {\n  from { background-position: 0 0; }\n  to { background-position: 0 48px; }\n}`,
  flicker: `@keyframes flicker {\n  0%, 100% { opacity: 0.15; }\n  50% { opacity: 0.9; }\n}`,
  mesh: `@keyframes mesh-drift {\n  0% { background-position: 0% 0%, 100% 0%, 50% 100%; }\n  50% { background-position: 30% 20%, 70% 40%, 20% 80%; }\n  100% { background-position: 0% 0%, 100% 0%, 50% 100%; }\n}`,
  spin: `@keyframes spin-slow { to { transform: rotate(360deg); } }`,
  leak: `@keyframes leak {\n  0% { transform: translateX(-30%) rotate(-12deg); opacity: 0.6; }\n  50% { transform: translateX(20%) rotate(-12deg); opacity: 1; }\n  100% { transform: translateX(-30%) rotate(-12deg); opacity: 0.6; }\n}`,
  twinkle: `@keyframes twinkle {\n  0%, 100% { opacity: 0.15; transform: scale(0.8); }\n  50% { opacity: 1; transform: scale(1.2); }\n}`,
  sonar: `@keyframes sonar {\n  from { transform: translate(-50%, -50%) scale(0.2); opacity: 0.6; }\n  to { transform: translate(-50%, -50%) scale(1); opacity: 0; }\n}`,
  dotPulse: `@keyframes dot-pulse {\n  0%, 100% { opacity: 0.12; transform: scale(0.7); }\n  50% { opacity: 0.6; transform: scale(1); }\n}`,
  ribbon: `@keyframes ribbon {\n  0% { transform: translateX(-10%) skewX(-18deg); }\n  50% { transform: translateX(10%) skewX(-18deg); }\n  100% { transform: translateX(-10%) skewX(-18deg); }\n}`,
  stripes: `@keyframes stripes {\n  from { background-position: 0 0; }\n  to { background-position: 56px 0; }\n}`,
};
const usage = (name: string, extra = "") => `import { ${name} } from "@/components/backgrounds/${name.replace("Background", "").replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "")}"\n\n<section className="relative overflow-hidden">\n  <${name}${extra} />\n  <div className="relative">…</div>\n</section>`;

export const backgrounds: BackgroundDoc[] = [
  { slug: "grid", name: "شبکه", file: bg("grid"), desc: "خط‌های نازک که به پایین محو می‌شوند؛ مناسب هیرو و بخش‌های فنی.", usage: usage("GridBackground", " size={56}"), props: [{ name: "size", type: "number", default: "56", desc: "اندازه‌ی هر خانه به پیکسل." }], promptBullets: ["Two 1px linear-gradients at 6% foreground opacity; mask fades toward the bottom.", "aria-hidden and pointer-events-none; sit inside a relative parent."] },
  { slug: "dots", name: "نقطه‌ای", file: bg("dots"), desc: "نقطه‌های ریز با محو شدن به پایین.", usage: usage("DotsBackground"), props: [{ name: "size", type: "number", default: "22", desc: "فاصله‌ی نقطه‌ها." }], promptBullets: ["1px radial-gradient under 12% opacity so Persian text stays readable."] },
  { slug: "girih", name: "گره", file: bg("girih"), desc: "ستاره‌ی هشت‌پر تکرارشونده، از هندسه‌ی کاشی ایرانی.", usage: usage("GirihBackground"), props: [{ name: "size", type: "number", default: "56", desc: "اندازه‌ی کاشی." }], notes: ["همان هندسه‌ی لوگو: دو مربع با چرخش ۴۵ درجه یک شمسه می‌سازند."], promptBullets: ["SVG tile of two squares (one rotate 45) as a data URL in background-image; neutral stroke with opacity.", "Radial mask so the center is stronger and edges fade."] },
  { slug: "hatch", name: "هاشور", file: bg("hatch"), desc: "خط‌های مورب برای نوارهای فاصله و بخش‌های در دست ساخت.", usage: usage("HatchBackground"), promptBullets: ["repeating-linear-gradient at −45deg, 1px stroke, 9px gap."] },
  { slug: "aurora", name: "شفق", file: bg("aurora"), css: KF.aurora, desc: "لکه‌های نور آرام در حرکت.", usage: usage("AuroraBackground"), promptBullets: ["Three large circles with blur-3xl and low opacity that drift via keyframes; negative delay so they are not in sync.", "Container overflow-hidden."] },
  { slug: "spotlight", name: "نور موضعی", file: bg("spotlight"), desc: "نور با ماوس جابه‌جا می‌شود و شبکه‌ی زیر را نشان می‌دهد.", usage: usage("SpotlightBackground"), props: [{ name: "radius", type: "number", default: "220", desc: "شعاع نور به پیکسل." }], promptBullets: ["onMouseMove stores percent position in state; radial-gradient at that point.", "Grid layer with a radial mask-image at the same center so only the lit area shows."] },
  { slug: "grain", name: "دانه", file: bg("grain"), desc: "بافت فیلم روی پس‌زمینه‌ی تیره.", usage: usage("GrainBackground"), props: [{ name: "opacity", type: "number", default: "0.7", desc: "شدت دانه." }], promptBullets: ["SVG feTurbulence (fractalNoise) as a data URL; mix-blend-screen on dark backgrounds."] },
  { slug: "retro-grid", name: "شبکه‌ی پرسپکتیو", file: bg("retro-grid"), css: KF.gridFlow, desc: "زمین شبکه‌ای که به سمت شما می‌آید.", usage: usage("RetroGridBackground"), promptBullets: ["Grid with rotateX(58deg) and perspective; animate background-position vertically for motion.", "A gradient fades the grid into the background toward the horizon."] },
  { slug: "mesh", name: "مش", file: bg("mesh"), desc: "چند گرادیان شعاعی روی هم، ثابت و سبک.", usage: usage("MeshBackground"), promptBullets: ["Three radial-gradients at different points using foreground and brand at low opacity."] },
  { slug: "flicker", name: "چشمک‌زن", file: bg("flicker"), css: KF.flicker, desc: "سلول‌هایی که نامنظم روشن می‌شوند.", usage: usage("FlickerBackground", " cols={12} rows={6}"), props: [{ name: "cols / rows", type: "number", default: "12 / 6", desc: "ابعاد شبکه." }], promptBullets: ["CSS grid with 1px gap; each cell's animation-delay and duration are pseudo-random from its index.", "Radial mask so edges fade."] },
  { slug: "rings", name: "حلقه‌ها", file: bg("rings"), desc: "دایره‌های هم‌مرکز با محو تدریجی.", usage: usage("RingsBackground"), props: [{ name: "gap", type: "number", default: "22", desc: "فاصله‌ی حلقه‌ها." }], promptBullets: ["repeating-radial-gradient from the center with a 1px stroke; radial mask."] },
  { slug: "gradient-mesh", name: "مش متحرک", file: bg("gradient-mesh"), css: KF.mesh, desc: "سه گرادیان شعاعی از رنگ‌های تم که آرام جابه‌جا می‌شوند؛ بدون تصویر.", usage: usage("GradientMeshBackground"), promptBullets: ["Three radial-gradients of brand, primary, and foreground at low opacity; background-size larger than 100% and animate background-position.", "Slow motion (15–20s) with ease-in-out so it does not distract."] },
  { slug: "conic-spin", name: "گرادیان چرخان", file: bg("conic-spin"), css: KF.spin, desc: "گرادیان مخروطی تار که پشت محتوا آهسته می‌چرخد؛ برای هیرو وقتی پس‌زمینه باید کمی بدرخشد.", usage: usage("ConicSpinBackground", " duration={24}"), props: [{ name: "duration", type: "number", default: "24", desc: "ثانیه برای یک دور." }], promptBullets: ["A circle larger than the container (140%) with conic-gradient and blur-3xl that rotates; container overflow-hidden.", "Colors from brand and foreground at 20–35% opacity."] },
  { slug: "light-leak", name: "نشت نور", file: bg("light-leak"), css: KF.leak, desc: "یک نوار نور گرم و مورب که آرام عبور می‌کند، مثل نشت نور فیلم.", usage: usage("LightLeakBackground"), promptBullets: ["Vertical band with a horizontal brand gradient, −12deg rotation and blur-2xl; slow translateX back and forth.", "Opacity oscillates between 0.6 and 1 so it breathes."] },
  { slug: "stars", name: "ستاره‌ها", file: bg("stars"), css: KF.twinkle, desc: "نقطه‌های ریز که هر کدام با ریتم خودشان چشمک می‌زنند.", usage: usage("StarsBackground", " count={60}"), props: [{ name: "count", type: "number", default: "60", desc: "تعداد ستاره." }], promptBullets: ["Position, size, and delay of each star come from its index (no Math.random) so SSR and client match.", "Twinkle on opacity and scale; sizes 1–3px."] },
  { slug: "sonar", name: "پژواک", file: bg("sonar"), css: KF.sonar, desc: "حلقه‌هایی که از مرکز بزرگ می‌شوند و محو می‌شوند؛ برای «در حال جست‌وجو» و نقشه.", usage: usage("SonarBackground", " rings={4}"), props: [{ name: "rings / duration", type: "number", default: "4 / 6", desc: "تعداد حلقه و مدت هر دور." }], promptBullets: ["Concentric circles with equal delays (duration ÷ rings) that scale up and fade.", "Center dot in brand with a glow shadow."] },
  { slug: "dot-wave", name: "موج نقطه‌ای", file: bg("dot-wave"), css: KF.dotPulse, desc: "شبکه‌ی نقطه که روشنایی‌اش به‌صورت موج قطری می‌گذرد.", usage: usage("DotWaveBackground", " cols={16} rows={8}"), props: [{ name: "cols / rows", type: "number", default: "16 / 8", desc: "ابعاد شبکه." }], promptBullets: ["Each dot's delay = (row + col) × 0.12s, modulo the animation duration; that makes the diagonal wave.", "Radial mask so edges fade."] },
  { slug: "aurora-ribbons", name: "نوار شفق", file: bg("aurora-ribbons"), css: KF.ribbon, desc: "نوارهای گرادیان مایل که آرام تاب می‌خورند؛ شفق قطبی با رنگ‌های تم.", usage: usage("AuroraRibbonsBackground"), promptBullets: ["Three vertical bands with a vertical gradient (transparent → color → transparent), negative skewX, blur-3xl, and horizontal drift with different delays.", "Colors from brand, foreground, and primary."] },
  { slug: "gradient-grain", name: "گرادیان دانه‌دار", file: bg("gradient-grain"), desc: "گرادیان گرم برند با بافت دانه روی آن؛ ثابت و پوستری.", usage: usage("GradientGrainBackground"), promptBullets: ["Diagonal linear-gradient from brand at 45% opacity to transparent; SVG noise on top with mix-blend-soft-light.", "No animation; for sections that should feel heavy and still."] },
  { slug: "moving-stripes", name: "راه‌راه روان", file: bg("moving-stripes"), css: KF.stripes, desc: "هاشور موربی که به‌آرامی سُر می‌خورد؛ حرکت بدون شلوغی.", usage: usage("MovingStripesBackground"), promptBullets: ["Diagonal repeating-linear-gradient with a fixed background-size; animate background-position by that width so the loop is seamless.", "Mask fades from top to bottom."] },
];
