import type { BackgroundDoc } from "./types";

const bg = (slug: string) => `registry/backgrounds/${slug}.tsx`;
const KF = {
  aurora: `@keyframes aurora {\n  0% { transform: translate(-10%, -10%) scale(1); }\n  50% { transform: translate(10%, 5%) scale(1.15); }\n  100% { transform: translate(-5%, 10%) scale(0.95); }\n}`,
  gridFlow: `@keyframes grid-flow {\n  from { background-position: 0 0; }\n  to { background-position: 0 48px; }\n}`,
  flicker: `@keyframes flicker {\n  0%, 100% { opacity: 0.15; }\n  50% { opacity: 0.9; }\n}`,
  mesh: `@keyframes mesh-drift {\n  0% { background-position: 0% 0%, 100% 0%, 50% 100%; }\n  50% { background-position: 30% 20%, 70% 40%, 20% 80%; }\n  100% { background-position: 0% 0%, 100% 0%, 50% 100%; }\n}`,
  spin: `@keyframes spin-slow { to { transform: rotate(360deg); } }`,
  leak: `@keyframes leak {\n  0% { transform: translateX(-30%) rotate(-12deg); opacity: 0.6; }\n  50% { transform: translateX(20%) rotate(-12deg); opacity: 1; }\n  100% { transform: translateX(-30%) rotate(-12deg); opacity: 0.6; }\n}`,
  twinkle: `@keyframes twinkle {\n  0%, 100% { opacity: 0.15; transform: scale(0.8); }\n  50% { opacity: 1; transform: scale(1.2); }\n}`,
  sonar: `@keyframes sonar {\n  from { transform: translate(-50%, -50%) scale(0.2); opacity: 0.6; }\n  to { transform: translate(-50%, -50%) scale(1); opacity: 0; }\n}`,
  dotPulse: `@keyframes dot-pulse {\n  0%, 100% { opacity: 0.12; transform: scale(0.7); }\n  50% { opacity: 0.6; transform: scale(1); }\n}`,
  ribbon: `@keyframes ribbon {\n  0% { transform: translateX(-10%) skewX(-18deg); }\n  50% { transform: translateX(10%) skewX(-18deg); }\n  100% { transform: translateX(-10%) skewX(-18deg); }\n}`,
  stripes: `@keyframes stripes {\n  from { background-position: 0 0; }\n  to { background-position: 56px 0; }\n}`,
};
const usage = (name: string, extra = "") => `import { ${name} } from "@/components/backgrounds/${name.replace("Background", "").replace(/([A-Z])/g, "-$1").toLowerCase().replace(/^-/, "")}"\n\n<section className="relative overflow-hidden">\n  <${name}${extra} />\n  <div className="relative">…</div>\n</section>`;
const SHADER_RULES = [
  "Built on the ShaderCanvas primitive (shader.tsx): raw WebGL 1, a full-screen clip-space quad, no library. The fragment shader is a template string in the same file.",
  "Free uniforms from the primitive: u_resolution, u_time, u_dpr, u_pointer, u_trail[8], and u_color0…u_color3 resolved from CSS variables (--brand, --foreground, …) so the theme drives the colors.",
  "Transparent canvas: write straight alpha in gl_FragColor. ShaderCanvas mixes onto the parent surface (u_surface) and outputs opaque pixels so Safari, which ignores canvas alpha, does not draw the effect on black. Keep alpha low; text goes on top.",
];
const shader = (opts: { opacity?: string; extraProps?: { name: string; type: string; default?: string; desc: string }[] } = {}) => ({
  engine: "webgl" as const,
  registryDeps: ["shader"],
  props: [
    ...(opts.extraProps ?? []),
    { name: "speed", type: "number", default: "1", desc: "ضریب سرعت زمان." },
    { name: "opacity", type: "number", default: opts.opacity ?? "0.5", desc: "بیشترین شفافیت لایه. کم نگهش دارید تا متن خوانا بمونه." },
  ],
});

export const backgrounds: BackgroundDoc[] = [
  { slug: "grid", name: "شبکه", file: bg("grid"), desc: "خط‌های نازکی که به پایین محو میشن، مناسب هیرو و بخش‌های فنی.", usage: usage("GridBackground", " size={56}"), props: [{ name: "size", type: "number", default: "56", desc: "اندازه‌ی هر خانه به پیکسل." }], promptBullets: ["Two 1px linear-gradients at 6% foreground opacity; mask fades toward the bottom.", "aria-hidden and pointer-events-none; sit inside a relative parent."] },
  { slug: "dots", name: "نقطه‌ای", file: bg("dots"), desc: "نقطه‌های ریزی که به پایین محو میشن.", usage: usage("DotsBackground"), props: [{ name: "size", type: "number", default: "22", desc: "فاصله‌ی نقطه‌ها." }], promptBullets: ["1px radial-gradient under 12% opacity so Persian text stays readable."] },
  { slug: "girih", name: "گره", file: bg("girih"), desc: "ستاره‌ی هشت‌پر تکرارشونده از هندسه‌ی کاشی ایرانی.", usage: usage("GirihBackground"), props: [{ name: "size", type: "number", default: "56", desc: "اندازه‌ی کاشی." }], notes: ["همان هندسه‌ی لوگو، یعنی دو مربع با چرخش ۴۵ درجه که یک شمسه می‌سازن."], promptBullets: ["SVG tile of two squares (one rotate 45) as a data URL in background-image; neutral stroke with opacity.", "Radial mask so the center is stronger and edges fade."] },
  { slug: "hatch", name: "هاشور", file: bg("hatch"), desc: "خط‌های مورب برای نوارهای فاصله و بخش‌های در دست ساخت.", usage: usage("HatchBackground"), promptBullets: ["repeating-linear-gradient at −45deg, 1px stroke, 9px gap."] },
  { slug: "aurora", name: "شفق", file: bg("aurora"), css: KF.aurora, desc: "لکه‌های نور آرامی که در حرکت‌اند.", usage: usage("AuroraBackground"), promptBullets: ["Three large circles with blur-3xl and low opacity that drift via keyframes; negative delay so they are not in sync.", "Container overflow-hidden."] },
  { slug: "spotlight", name: "نور موضعی", file: bg("spotlight"), desc: "نوری که با ماوس جابه‌جا میشه و شبکه‌ی زیرش را نشان میده.", usage: usage("SpotlightBackground"), props: [{ name: "radius", type: "number", default: "220", desc: "شعاع نور به پیکسل." }], promptBullets: ["onMouseMove stores percent position in state; radial-gradient at that point.", "Grid layer with a radial mask-image at the same center so only the lit area shows."] },
  { slug: "grain", name: "دانه", file: bg("grain"), desc: "بافت فیلم روی پس‌زمینه‌ی تیره.", usage: usage("GrainBackground"), props: [{ name: "opacity", type: "number", default: "0.7", desc: "شدت دانه." }], promptBullets: ["SVG feTurbulence (fractalNoise) as a data URL; mix-blend-screen on dark backgrounds."] },
  { slug: "retro-grid", name: "شبکه‌ی پرسپکتیو", file: bg("retro-grid"), css: KF.gridFlow, desc: "زمین شبکه‌ای که به سمت شما می‌آد.", usage: usage("RetroGridBackground"), promptBullets: ["Grid with rotateX(58deg) and perspective; animate background-position vertically for motion.", "A gradient fades the grid into the background toward the horizon."] },
  { slug: "mesh", name: "مش", file: bg("mesh"), desc: "چند گرادیان شعاعی روی هم، ثابت و سبک.", usage: usage("MeshBackground"), promptBullets: ["Three radial-gradients at different points using foreground and brand at low opacity."] },
  { slug: "flicker", name: "چشمک‌زن", file: bg("flicker"), css: KF.flicker, desc: "سلول‌هایی که نامنظم روشن میشن.", usage: usage("FlickerBackground", " cols={12} rows={6}"), props: [{ name: "cols / rows", type: "number", default: "12 / 6", desc: "ابعاد شبکه." }], promptBullets: ["CSS grid with 1px gap; each cell's animation-delay and duration are pseudo-random from its index.", "Radial mask so edges fade."] },
  { slug: "rings", name: "حلقه‌ها", file: bg("rings"), desc: "دایره‌های هم‌مرکز با محو تدریجی.", usage: usage("RingsBackground"), props: [{ name: "gap", type: "number", default: "22", desc: "فاصله‌ی حلقه‌ها." }], promptBullets: ["repeating-radial-gradient from the center with a 1px stroke; radial mask."] },
  { slug: "gradient-mesh", name: "مش متحرک", file: bg("gradient-mesh"), css: KF.mesh, desc: "سه گرادیان شعاعی از رنگ‌های تم که آرام جابه‌جا میشن، بدون هیچ تصویری.", usage: usage("GradientMeshBackground"), promptBullets: ["Three radial-gradients of brand, primary, and foreground at low opacity; background-size larger than 100% and animate background-position.", "Slow motion (15–20s) with ease-in-out so it does not distract."] },
  { slug: "conic-spin", name: "گرادیان چرخان", file: bg("conic-spin"), css: KF.spin, desc: "گرادیان مخروطی تاری که پشت محتوا آهسته می‌چرخه، برای هیرویی که باید کمی بدرخشد.", usage: usage("ConicSpinBackground", " duration={24}"), props: [{ name: "duration", type: "number", default: "24", desc: "ثانیه برای یک دور." }], promptBullets: ["A circle larger than the container (140%) with conic-gradient and blur-3xl that rotates; container overflow-hidden.", "Colors from brand and foreground at 20–35% opacity."] },
  { slug: "light-leak", name: "نشت نور", file: bg("light-leak"), css: KF.leak, desc: "نوار نور گرم و موربی که آرام عبور می‌کنه، مثل نشت نور در فیلم.", usage: usage("LightLeakBackground"), promptBullets: ["Vertical band with a horizontal brand gradient, −12deg rotation and blur-2xl; slow translateX back and forth.", "Opacity oscillates between 0.6 and 1 so it breathes."] },
  { slug: "stars", name: "ستاره‌ها", file: bg("stars"), css: KF.twinkle, desc: "نقطه‌های ریزی که هر کدام با ریتم خودشون چشمک می‌زنن.", usage: usage("StarsBackground", " count={60}"), props: [{ name: "count", type: "number", default: "60", desc: "تعداد ستاره." }], promptBullets: ["Position, size, and delay of each star come from its index (no Math.random) so SSR and client match.", "Twinkle on opacity and scale; sizes 1–3px."] },
  { slug: "sonar", name: "پژواک", file: bg("sonar"), css: KF.sonar, desc: "حلقه‌هایی که از مرکز بزرگ و محو میشن، برای «در حال جست‌وجو» و نقشه.", usage: usage("SonarBackground", " rings={4}"), props: [{ name: "rings / duration", type: "number", default: "4 / 6", desc: "تعداد حلقه و مدت هر دور." }], promptBullets: ["Concentric circles with equal delays (duration ÷ rings) that scale up and fade.", "Center dot in brand with a glow shadow."] },
  { slug: "dot-wave", name: "موج نقطه‌ای", file: bg("dot-wave"), css: KF.dotPulse, desc: "شبکه‌ای از نقطه که روشنایی‌اش به شکل موج قطری می‌گذره.", usage: usage("DotWaveBackground", " cols={16} rows={8}"), props: [{ name: "cols / rows", type: "number", default: "16 / 8", desc: "ابعاد شبکه." }], promptBullets: ["Each dot's delay = (row + col) × 0.12s, modulo the animation duration; that makes the diagonal wave.", "Radial mask so edges fade."] },
  { slug: "aurora-ribbons", name: "نوار شفق", file: bg("aurora-ribbons"), css: KF.ribbon, desc: "نوارهای گرادیان مایلی که آرام تاب می‌خورن، شفق قطبی با رنگ‌های تم.", usage: usage("AuroraRibbonsBackground"), promptBullets: ["Three vertical bands with a vertical gradient (transparent → color → transparent), negative skewX, blur-3xl, and horizontal drift with different delays.", "Colors from brand, foreground, and primary."] },
  { slug: "gradient-grain", name: "گرادیان دانه‌دار", file: bg("gradient-grain"), desc: "گرادیان گرم برند با بافت دانه روی آن، ثابت و پوستری.", usage: usage("GradientGrainBackground"), promptBullets: ["Diagonal linear-gradient from brand at 45% opacity to transparent; SVG noise on top with mix-blend-soft-light.", "No animation; for sections that should feel heavy and still."] },
  { slug: "moving-stripes", name: "راه‌راه روان", file: bg("moving-stripes"), css: KF.stripes, desc: "هاشور موربی که به‌آرامی سُر می‌خوره، حرکت بدون شلوغی.", usage: usage("MovingStripesBackground"), promptBullets: ["Diagonal repeating-linear-gradient with a fixed background-size; animate background-position by that width so the loop is seamless.", "Mask fades from top to bottom."] },

  // ---- WebGL shaders. All of them import ShaderCanvas from shader.tsx. ----
  {
    slug: "shader", name: "بوم شیدر", engine: "webgl", file: bg("shader"),
    desc: "پایه‌ی همه‌ی شیدرها با WebGL خام و بدون کتابخانه. شیدر خودتون را بنویسید و رنگ‌ها را از توکن‌های تم بگیرید تا با عوض شدن تم به‌روز بشن.",
    usage: `import { ShaderCanvas, GLSL_NOISE } from "@/components/backgrounds/shader"

const frag = /* glsl */ \`
void main() {
  vec2 uv = gl_FragCoord.xy / u_resolution;
  float glow = smoothstep(0.7, 0.0, distance(uv, u_pointer));
  vec3 color = mix(u_color0, u_color1, uv.y);
  gl_FragColor = vec4(color, glow * 0.35);
}\`

<section className="relative overflow-hidden">
  <ShaderCanvas fragment={frag} colors={["--brand", "--foreground"]} pointer />
  <div className="relative">…</div>
</section>`,
    props: [
      { name: "fragment", type: "string", desc: "بدنه‌ی شیدر فرگمنت (GLSL ES 1.00) با یک main. هدر یونیفرم‌ها خودکار اضافه میشه." },
      { name: "colors", type: "string[]", default: '["--brand", "--foreground", "--background"]', desc: "متغیرهای CSS که به u_color0 تا u_color3 تبدیل میشن." },
      { name: "uniforms", type: "Record<string, number | number[]>", desc: "یونیفرم‌های دلخواه. عدد به float و آرایه به vec2 تا vec4 تبدیل میشه." },
      { name: "speed", type: "number", default: "1", desc: "ضریب u_time." },
      { name: "pointer", type: "boolean", default: "false", desc: "حرکت ماوس روی والد را به u_pointer و u_trail می‌فرسته." },
      { name: "dpr", type: "number", default: "Safari: min(round(dpr), 2); else min(dpr, 1.5)", desc: "مقیاس رندر. کمتر یعنی سبک‌تر. در سافاری عدد صحیح می‌مونه تا بوم تار نشه." },
    ],
    notes: [
      "یونیفرم‌های آماده این‌ها هستن: u_resolution، u_time، u_dpr، u_pointer، u_trail[8] و u_color0 تا u_color3. برای نویز و fbm، رشته‌ی GLSL_NOISE را به ابتدای شیدر اضافه کنید.",
      "بوم شفافه، پس آلفای خروجی را کم نگه دارید. بیرون از دید، حلقه‌ی رندر می‌ایسته و کانتکست آزاد میشه و با prefers-reduced-motion فقط یک فریم کشیده میشه.",
      "Chrome بیش از ۱۶ کانتکست WebGL فعال را نگه نمی‌داره، برای همین این کامپوننت با IntersectionObserver فقط برای بوم‌های در دید کانتکست می‌سازه.",
    ],
    promptBullets: [
      "Create a WebGL 1 context on a canvas (prefer alpha false) and draw a clip-space quad with the user's fragment shader; prepend a header that declares u_resolution, u_time, u_dpr, u_pointer, u_trail[8], u_color0…u_color3, u_surface and enables OES_standard_derivatives. Wrap main() to mix straight-alpha output onto u_surface (parent background) and write opaque pixels, because Safari ignores canvas alpha and would otherwise show the effect on black.",
      "Resolve each CSS variable in `colors` to sRGB by painting it on a 1×1 2D canvas (colorSpace srgb) and reading the pixel (works for oklch); re-resolve when a data-theme attribute changes anywhere (MutationObserver, subtree).",
      "ResizeObserver sizes the drawing buffer (integer devicePixelRatio capped at 2 on WebKit, else 1.5) using drawingBufferWidth/Height for the viewport; IntersectionObserver starts the rAF loop when visible and calls WEBGL_lose_context.loseContext() when hidden or on unmount, restoring on re-entry.",
      "Under prefers-reduced-motion draw a single frame (u_time = 4) and redraw only on resize, theme, or pointer changes.",
      "Optional pointer mode listens to pointermove on the parent element and keeps a ring buffer of the last 8 positions with timestamps for trail effects.",
      "Export GLSL_NOISE (hash, value noise, 5-octave fbm) so other shaders can prepend it.",
    ],
  },
  { slug: "silk", name: "ابریشم", file: bg("silk"), ...shader({ opacity: "0.35", extraProps: [{ name: "scale", type: "number", default: "1.6", desc: "تراکم چین‌ها." }] }), desc: "موج‌های نرم و براق که مثل پارچه‌ی ساتن تاب می‌خورن.", usage: usage("SilkBackground"), promptBullets: [...SHADER_RULES, "Fold the UV with nested sines: shift q.y by sin(6q.x − t), then v = 0.5 + 0.5·sin(5·(q.x + q.y + cos(3q.x + 5q.y)) + sin(20·(q.x + q.y))); pow(v, 1.6) for sheen.", "Mix brand into foreground by v; alpha = v × opacity."] },
  { slug: "fog", name: "مه", file: bg("fog"), ...shader({ opacity: "0.35", extraProps: [{ name: "scale", type: "number", default: "2.2", desc: "درشتی توده‌های مه." }] }), desc: "مه آرامی که با نویز چندلایه جابه‌جا میشه و به پایین محو میشه.", usage: usage("FogBackground"), promptBullets: [...SHADER_RULES, "fbm(p + drift + fbm(p·0.6 − t)·1.2) then smoothstep(0.35, 0.95) so only the dense parts show; foreground color only.", "Vertical smoothstep mask so the bottom stays clear for text."] },
  { slug: "nebula", name: "سحابی", file: bg("nebula"), ...shader({ opacity: "0.4", extraProps: [{ name: "scale", type: "number", default: "1.4", desc: "درشتی ابرها." }] }), desc: "نویز پیچ‌خورده در هم، شبیه ابرهای گاز، با رنگ برند و پیش‌زمینه.", usage: usage("NebulaBackground"), promptBullets: [...SHADER_RULES, "Domain warping: q = fbm(p), r = fbm(p + 4q), f = fbm(p + 3r); color from foreground toward brand by length(q) and r.x.", "Alpha = smoothstep(0.25, 0.85, f²·2.2) × opacity; time scaled by 0.06 so it barely moves."] },
  { slug: "contour", name: "خطوط تراز", file: bg("contour"), ...shader({ opacity: "0.45", extraProps: [{ name: "scale", type: "number", default: "1.2", desc: "درشتی پستی‌وبلندی." }, { name: "levels", type: "number", default: "14", desc: "تعداد خط تراز." }] }), desc: "خط‌های نقشه‌ی توپوگرافی که آهسته جابه‌جا میشن و هر چهارمین خط پررنگ‌تره.", usage: usage("ContourBackground"), promptBullets: [...SHADER_RULES, "h = fbm(p + drift) × levels; line where fract(h) ≈ 0.5 with fwidth(h) for a constant 1px width; every 4th level is brighter.", "Radial mask so the edges fade; foreground color only."] },
  { slug: "voronoi", name: "سلول‌ها", file: bg("voronoi"), ...shader({ opacity: "0.4", extraProps: [{ name: "scale", type: "number", default: "5", desc: "تعداد سلول در ارتفاع." }] }), desc: "سلول‌های ورونوی با مرزهای نازک که مرکزشون آرام می‌لغزه.", usage: usage("VoronoiBackground"), promptBullets: [...SHADER_RULES, "3×3 neighbor search; sites orbit their cell center with sin/cos of hashed phases; border = second-closest minus closest with fwidth anti-aliasing.", "A faint per-cell shade from hash(cell) plus a radial mask."] },
  { slug: "warp-grid", name: "شبکه‌ی موج‌دار", file: bg("warp-grid"), ...shader({ opacity: "0.35", extraProps: [{ name: "scale", type: "number", default: "10", desc: "تعداد خانه در ارتفاع." }, { name: "warp", type: "number", default: "0.25", desc: "شدت پیچ‌خوردگی." }] }), desc: "شبکه‌ای که با نویز پیچ می‌خوره، مثل کاغذ شطرنجی زیر آب.", usage: usage("WarpGridBackground"), promptBullets: [...SHADER_RULES, "Displace UV by (fbm, fbm) − 0.5 times warp, then draw grid lines with fwidth so they stay 1px after the distortion.", "Mask fades toward the bottom."] },
  { slug: "godrays", name: "پرتو نور", file: bg("godrays"), ...shader({ opacity: "0.45" }), desc: "پرتوهای نوری که از بالا می‌تابن و آرام تکان می‌خورن.", usage: usage("GodraysBackground"), promptBullets: [...SHADER_RULES, "Polar coordinates around a source above the top edge; rays = products of sines of the angle at two frequencies, modulated by noise; pow for contrast.", "Falloff by distance from the source; brand color."] },
  { slug: "water-ripple", name: "موج آب", file: bg("water-ripple"), ...shader({ opacity: "0.6" }), desc: "حلقه‌های آبی که با حرکت ماوس پخش میشن و بدون ماوس هم گاهی قطره‌ای می‌افته.", usage: usage("WaterRippleBackground"), notes: ["والد باید رویداد ماوس بگیره، چون خود بوم pointer-events نداره تا مزاحم کلیک نشه."], promptBullets: [...SHADER_RULES, "pointer mode: each entry of u_trail is a drop; ring = sin((r − front)·80)·exp(−|r − front|·18) with front = age·0.35, decaying by exp(−age·1.6) and clipped to the front.", "Three automatic drops from hash(floor(time)) so the layer is alive without a pointer; a faint fbm caustic underneath."] },
  { slug: "dither", name: "دیترینگ", file: bg("dither"), ...shader({ extraProps: [{ name: "pixel", type: "number", default: "3", desc: "اندازه‌ی هر پیکسل دیتر به px." }] }), desc: "گرادیان متحرک با نقطه‌های Bayer به سبک نمایشگرهای قدیمی، که وسطش خالی می‌مونه.", usage: usage("DitherBackground"), promptBullets: [...SHADER_RULES, "Quantize gl_FragCoord to pixel × dpr blocks; value = fbm of the block position × a radial vignette (clear center); on = step(bayer4(block), value) with the compact Bayer formula bayer2(a) = fract(a.x/2 + a.y²·0.75).", "One bit output in the foreground color; no smoothing."] },
  { slug: "halftone", name: "ترام", file: bg("halftone"), ...shader({ opacity: "0.45", extraProps: [{ name: "cell", type: "number", default: "10", desc: "فاصله‌ی نقطه‌ها به px." }] }), desc: "نقطه‌های ترام چاپ که اندازه‌شون با یک موج نرم عوض میشه.", usage: usage("HalftoneBackground"), promptBullets: [...SHADER_RULES, "Rotate pixel coordinates ~30°, split into cells of cell × dpr px, and size each dot by fbm sampled at the cell center; smoothstep the circle edge by 1px.", "Radial mask; foreground color."] },
  { slug: "waves", name: "امواج", file: bg("waves"), ...shader({ opacity: "0.55", extraProps: [{ name: "lines", type: "number", default: "12", desc: "تعداد خط (تا ۱۶)." }] }), desc: "خط‌های سینوسی روی هم که مثل رشته‌های نور موج می‌زنن.", usage: usage("WavesBackground"), promptBullets: [...SHADER_RULES, "Up to 16 lines in a constant loop; each y = base + two sines + a little noise; 1px width from 1/u_resolution.y; brightness travels along x with a third sine.", "Horizontal mask so the lines fade at both ends."] },
  { slug: "plasma", name: "پلاسما", file: bg("plasma"), ...shader({ opacity: "0.3", extraProps: [{ name: "scale", type: "number", default: "3", desc: "درشتی موج‌ها." }] }), desc: "پلاسمای کلاسیک دموسین، آهسته و کم‌نور، با رنگ برند و پیش‌زمینه.", usage: usage("PlasmaBackground"), promptBullets: [...SHADER_RULES, "Sum of four sines (x, y, x+y, and distance to a drifting center) scaled to −1…1; alpha = smoothstep of 0.5 + 0.5·sin(v·π); color mixes brand into foreground by a phase-shifted sine.", "Radial mask so the edges fade; time scaled by 0.3."] },
  { slug: "truchet", name: "تروشه", file: bg("truchet"), ...shader({ opacity: "0.4", extraProps: [{ name: "scale", type: "number", default: "8", desc: "تعداد کاشی در ارتفاع." }] }), desc: "کاشی‌های ربع‌دایره که گاهی می‌چرخن و مسیر هزارتو را عوض می‌کنن.", usage: usage("TruchetBackground"), promptBullets: [...SHADER_RULES, "Each cell draws two quarter-circle arcs (radius 0.5 around opposite corners); hash(cell + floor(time·0.12 + hash·7)) decides the flip so cells re-roll at their own phase.", "fwidth for a constant 1px stroke; a diagonal sine wave of brightness travels across the cells; radial mask; foreground color."] },
  { slug: "hex-grid", name: "شش‌ضلعی", file: bg("hex-grid"), ...shader({ opacity: "0.4", extraProps: [{ name: "scale", type: "number", default: "7", desc: "تعداد شش‌ضلعی در ارتفاع." }] }), desc: "لانه‌زنبوری با مرزهای نازک که چند خانه‌اش با عبور یک میدان نویز روشن میشن.", usage: usage("HexGridBackground"), promptBullets: [...SHADER_RULES, "Hex tiling with the two-offset-grid trick (S = (1, √3)); hexDist(p) = max(dot(|p|, S/2), |p|.x) so the edge sits at 0.5, drawn with fwidth.", "Cell glow = smoothstep(0.55, 0.9, noise(cellId·0.35 + drift)); radial mask; foreground color."] },
  { slug: "marble", name: "مرمر", file: bg("marble"), ...shader({ opacity: "0.35", extraProps: [{ name: "scale", type: "number", default: "1.5", desc: "درشتی رگه‌ها." }] }), desc: "رگه‌های سنگ مرمر از نویز پیچ‌خورده، که به‌کندی جابه‌جا میشن.", usage: usage("MarbleBackground"), promptBullets: [...SHADER_RULES, "q = (fbm(p + t), fbm(p + offset − t)); v = fbm(p + 2.5q); veins = pow(1 − |sin((x + y)·1.5 + v·8)|, 4) for sharp lines.", "Foreground body at 35% of smoothstep(v); veins tinted slightly toward brand; time scaled by 0.04."] },
  { slug: "metaballs", name: "گوی‌های چسبناک", file: bg("metaballs"), ...shader({ opacity: "0.35", extraProps: [{ name: "count", type: "number", default: "6", desc: "تعداد گوی (تا ۱۲)." }] }), desc: "گوی‌هایی که در هم می‌روند و جدا میشن، مثل چراغ گدازه.", usage: usage("MetaballsBackground"), promptBullets: [...SHADER_RULES, "Up to 12 balls in a constant loop; each orbits on sin/cos with hashed frequencies and phases; field f = Σ r²/d².", "Body = smoothstep(0.9, 1.5, f); rim = band around f ≈ 1 tinted toward foreground; brand fill."] },
  { slug: "kaleidoscope", name: "کلایدوسکوپ", file: bg("kaleidoscope"), ...shader({ opacity: "0.35", extraProps: [{ name: "segments", type: "number", default: "8", desc: "تعداد پره‌ها." }] }), desc: "نویزی که در پره‌های آینه‌ای تا می‌خوره و دور مرکز آرام می‌چرخه.", usage: usage("KaleidoscopeBackground"), promptBullets: [...SHADER_RULES, "Polar fold: a = |mod(angle + slow spin, 2π/n) − π/n|, then p = (cos a, sin a)·r; fbm at p plus rings from sin(r·20 − t + fbm·6).", "Radial mask so the outer area stays clear for text; brand toward foreground by the noise value."] },
  { slug: "cursor-trail", name: "رد ماوس", file: bg("cursor-trail"), ...shader({ opacity: "0.6" }), desc: "دنباله‌ی نورانی که دنبال ماوس می‌آد و وقتی ماوس ساکته، خودش می‌گرده.", usage: usage("CursorTrailBackground"), notes: ["والد باید رویداد ماوس بگیره، چون خود بوم pointer-events نداره تا مزاحم کلیک نشه."], promptBullets: [...SHADER_RULES, "pointer mode: glow dots at each u_trail entry (exp(−d·70)·exp(−age·1.4)) plus glow segments between consecutive entries when 0 < Δt < 0.5s; the wrap pair (7 → 0) is checked the same way so the ring buffer never draws a stray line.", "When the newest entry is older than ~1.5s, a synthetic comet on a Lissajous path fades in so the layer is never empty."] },
  { slug: "particles", name: "ذرات شناور", file: bg("particles"), ...shader({ opacity: "0.6", extraProps: [{ name: "density", type: "number", default: "1", desc: "تراکم ذرات." }] }), desc: "غبار نرمی در سه عمق که بالا می‌ره، تاب می‌خوره و چشمک می‌زنه.", usage: usage("ParticlesBackground"), promptBullets: [...SHADER_RULES, "One particle per grid cell (3×3 neighbor search) with hashed offset, radius, and twinkle phase; three layers at different scales and drift speeds for parallax; cell ids wrapped with mod 64 so hashes stay precise over time.", "Gaussian dots (exp(−d²/r²·3)); vertical mask so the top and bottom fade; foreground color."] },
  { slug: "moire", name: "مواره", file: bg("moire"), ...shader({ opacity: "0.3", extraProps: [{ name: "gap", type: "number", default: "7", desc: "فاصله‌ی حلقه‌ها به px." }] }), desc: "دو دسته حلقه‌ی ریز که مرکزشون می‌لغزه و تداخلشون نوارهای بزرگ و آرام می‌سازه.", usage: usage("MoireBackground"), promptBullets: [...SHADER_RULES, "Two ring fields 0.5 + 0.5·sin(dist·freq) with freq from the px gap (2π·height/(gap·dpr)); the second at 1.03× frequency; multiply them for the interference.", "Centers orbit slowly; smoothstep(0.3, 0.9) and a radial mask; foreground color."] },
  { slug: "scanlines", name: "اسکن‌لاین", file: bg("scanlines"), ...shader({ opacity: "0.3", extraProps: [{ name: "gap", type: "number", default: "3", desc: "فاصله‌ی خط‌ها به px." }] }), desc: "خط‌های فسفری CRT با یک نوار روان، کمی برفک و وینیت.", usage: usage("ScanlinesBackground"), promptBullets: [...SHADER_RULES, "Lines from sin(gl_FragCoord.y / (gap·dpr) · 2π) sharpened by smoothstep; a rolling bar from fract(uv.y − t·0.05); per-pixel hash grain refreshed 12×/s at 12%; slow noise flicker (±10%) instead of fast strobing.", "Vignette from distance to center; foreground color."] },
  { slug: "iso-cubes", name: "مکعب‌های ایزومتریک", file: bg("iso-cubes"), ...shader({ opacity: "0.35", extraProps: [{ name: "scale", type: "number", default: "6", desc: "تعداد مکعب در ارتفاع." }] }), desc: "میدانی از مکعب‌های ایزومتریک که با یک نویز کند نفس می‌کشن.", usage: usage("IsoCubesBackground"), promptBullets: [...SHADER_RULES, "Hex tiling; the angle inside each hex, offset by 30° and divided by 120°, picks one of three rhombi (top 1.0, left 0.55, right 0.3 shade).", "Hex edges and the three spokes drawn with fwidth; per-cube brightness from noise(cellId·0.4 + drift); radial mask; foreground color."] },
  { slug: "liquid-gradient", name: "گرادیان سیال", file: bg("liquid-gradient"), ...shader({ opacity: "0.45" }), desc: "سه رنگ تم که با نویز روان در هم می‌روند و ماوس میدان را به سمت خودش می‌کشه.", usage: usage("LiquidGradientBackground"), notes: ["والد باید رویداد ماوس بگیره، چون خود بوم pointer-events نداره تا مزاحم کلیک نشه."], promptBullets: [...SHADER_RULES, "pointer mode: pull = exp(−|p − pointer|²·3) displaces the sample point toward the pointer; two fbm fields drive mixes brand → primary → foreground.", "Alpha = smoothstep(0.25, 0.75, n1)·0.6 + pull·0.3, so the pointer leaves a soft highlight."] },
];
