import type { TemplateDoc } from "./types";

const tp = (slug: string) => `registry/templates/${slug}.tsx`;
const usage = (name: string, slug: string) => `// app/${slug}/page.tsx\nimport { ${name} } from "@/components/templates/${slug}"\n\nexport default function Page() {\n  return <${name} />\n}`;

export const templates: TemplateDoc[] = [
  { slug: "shop-dashboard", name: "داشبورد فروشگاه", file: tp("shop-dashboard"), tags: ["داشبورد", "جدول", "آمار"], pages: 1, desc: "آمار فروش، نمودار هفتگی، سفارش‌های اخیر و هدف ماهانه در یک نگاه.", usage: usage("ShopDashboard", "shop-dashboard"), registryDeps: ["sidebar", "stat", "table", "badge", "avatar", "progress", "button", "input"], promptBullets: ["Right sidebar with groups and numeric badges; header with search and avatar.", "Four stat cards, weekly bar chart with days ش to ج, recent-orders table with تومان and status."] },
  { slug: "auth", name: "ورود و ثبت‌نام", file: tp("auth"), tags: ["فرم", "کد تأیید"], pages: 1, desc: "ورود با شماره‌ی موبایل و کد تأیید پیامکی، در دو مرحله.", usage: usage("AuthPage", "auth"), registryDeps: ["input", "otp-field", "button", "stepper"], promptBullets: ["Step 1: mobile number with +98 prefix and an ltr field. Step 2: six OTP cells with a resend countdown.", "Centered card on a grid background; logo on top, terms link at the bottom."] },
  { slug: "startup-landing", name: "لندینگ استارتاپ", file: tp("startup-landing"), tags: ["لندینگ", "قیمت", "پرسش‌ها"], pages: 1, desc: "هیرو، سه ویژگی، سه پلن قیمت و پرسش‌های متداول.", usage: usage("StartupLanding", "startup-landing"), registryDeps: ["button", "badge", "card", "accordion", "price"], promptBullets: ["RTL hero with a large headline, two buttons, and a customer-logo bar.", "Pricing with three plans in تومان, middle plan highlighted; FAQ accordion."] },
  { slug: "pricing", name: "صفحه‌ی قیمت‌گذاری", file: tp("pricing"), tags: ["قیمت", "تب"], pages: 1, desc: "سه پلن با تومان، تغییر ماهانه/سالانه و جدول مقایسه.", usage: usage("PricingPage", "pricing"), registryDeps: ["tabs", "price", "button", "badge"], promptBullets: ["Monthly/yearly tabs that swap prices and show a savings percent.", "Three cards with a feature list and checkmarks; recommended plan with a stronger border and a «محبوب» badge."] },
  { slug: "ai-chat", name: "چت هوش مصنوعی", file: tp("ai-chat"), tags: ["چت", "استریم", "پرامپت"], pages: 1, desc: "گفت‌وگو با حباب‌های پیام، فراخوانی ابزار و جعبه‌ی پرامپت فارسی.", usage: usage("AiChat", "ai-chat"), registryDeps: ["prompt-input", "avatar", "badge", "kbd"], promptBullets: ["User message on the right with secondary background; model reply further left with an avatar.", "Tool-call card with a mono function name and result; prompt box stuck to the bottom."] },
  { slug: "invoice", name: "فاکتور", file: tp("invoice"), tags: ["چاپ", "جدول", "شمسی"], pages: 1, desc: "پیش‌فاکتور قابل چاپ با تاریخ شمسی، جدول اقلام و جمع کل.", usage: usage("InvoicePage", "invoice"), registryDeps: ["table", "badge", "button"], promptBullets: ["Header with shop name, invoice number, and Jalali date; line-item table with qty, unit price, and total.", "Grand total, tax, and amount due in تومان; print: styles that hide buttons."] },
  { slug: "blog", name: "وبلاگ", file: tp("blog"), tags: ["محتوا", "خواندن"], pages: 1, desc: "صفحه‌ی مطلب با فهرست مطالب، تایپوگرافی خواندنی و کارت نویسنده.", usage: usage("BlogPost", "blog"), registryDeps: ["avatar", "badge", "breadcrumb"], promptBullets: ["Text column max ~65 characters wide with line-height 1.9; sticky table of contents in the side column.", "Jalali date and reading time with Persian digits; author card at the end."] },
  { slug: "settings", name: "پنل تنظیمات", file: tp("settings"), tags: ["فرم", "کلید"], pages: 1, desc: "پروفایل، امنیت و اعلان‌ها با ناوبری کناری.", usage: usage("SettingsPage", "settings"), registryDeps: ["sidebar", "input", "switch", "button", "avatar", "radio-group"], promptBullets: ["Settings nav on the right; each section is a card with a title and description.", "Switch rows with title and helper text; save button at the bottom of each card."] },
  { slug: "checkout", name: "پرداخت", file: tp("checkout"), tags: ["فروشگاه", "چندمرحله‌ای"], pages: 1, desc: "سبد → آدرس → پست/پیک → درگاه، با خلاصه‌ی سفارش چسبان و کد تخفیف.", usage: usage("CheckoutPage", "checkout"), registryDeps: ["stepper", "number-field", "phone-input", "radio-group", "select", "textarea", "input", "badge", "button"], promptBullets: ["Four steps with Stepper; show only the current section, with prev/next buttons at the bottom.", "Shipping as radio cards with each method's fee; gateways as cards too; sticky order summary with تومان totals."] },
  { slug: "store", name: "فروشگاه", file: tp("store"), tags: ["فروشگاه", "محصول", "سبد"], pages: 1, desc: "صفحه‌ی محصول به سبک فروشگاه‌های ایرانی: گالری، مشخصات، جعبه‌ی فروشنده با گارانتی و ارسال، سبد کشویی و کالاهای مشابه.", usage: usage("StorePage", "store"), registryDeps: ["breadcrumb", "price", "rating", "tabs", "sheet", "carousel", "number-field", "badge", "button"], promptBullets: ["Three columns: gallery (4), details (5), seller box (3) with price, discount, quantity, and add-to-cart.", "Cart as a sheet from the right; similar products in an RTL carousel."] },
  { slug: "onboarding", name: "ثبت‌نام پیامکی", file: tp("onboarding"), tags: ["فرم", "کد تأیید"], pages: 1, desc: "موبایل → کد تأیید → پروفایل → پایان، در یک کارت با مراحل.", usage: usage("OnboardingPage", "onboarding"), registryDeps: ["phone-input", "otp-field", "stepper", "radio-group", "input", "button"], promptBullets: ["Send-code button disabled until the number is valid; OTP onComplete advances automatically.", "Last step with a success-check animation and two buttons."] },
  { slug: "admin-orders", name: "مدیریت سفارش‌ها", file: tp("admin-orders"), tags: ["ادمین", "جدول", "شمسی"], pages: 1, desc: "جدول داده با فیلتر تاریخ شمسی و وضعیت، نشان‌های وضعیت، منوی عمل و سه کارت آمار.", usage: usage("AdminOrdersPage", "admin-orders"), registryDeps: ["data-table", "date-picker", "select", "dropdown-menu", "badge", "stat", "avatar"], promptBullets: ["Columns: number (mono), customer with avatar, Jalali date, items, تومان amount, status Badge, overflow menu.", "Filters in the table toolbar: status (Select) and «از تاریخ» (Jalali DatePicker) with a clear button."] },
  { slug: "booking", name: "رزرو نوبت", file: tp("booking"), tags: ["کلینیک", "سالن", "تقویم"], pages: 1, desc: "سرویس، روز روی تقویم شمسی (جمعه‌ها تعطیل)، ساعت‌های خالی و تأیید با بیعانه.", usage: usage("BookingPage", "booking"), registryDeps: ["calendar", "radio-group", "phone-input", "badge", "avatar", "button"], promptBullets: ["Jalali calendar with min=today; Friday selection shows a closed message; booked slots line-through and disabled.", "Sticky confirm column with service, weekday name, time, and a 30% deposit."] },
  { slug: "wallet", name: "کیف پول", file: tp("wallet"), tags: ["مالی", "شبا"], pages: 1, desc: "کارت موجودی با شماره‌انداز، شارژ سریع، تراکنش‌ها با تاریخ شمسی و برداشت به شبا در پنجره.", usage: usage("WalletPage", "wallet"), registryDeps: ["iban-input", "dialog", "tabs", "badge", "input", "button"], promptBullets: ["Balance with Odometer and a hide button; transactions with in/out arrows and «در انتظار تسویه».", "Withdraw in a Dialog: validated Sheba, amount with thousands separator, and an «بیشتر از موجودی» error."] },
  { slug: "error-pages", name: "صفحه‌های خطا", file: tp("error-pages"), tags: ["۴۰۴", "خالی", "آفلاین"], pages: 4, desc: "۴۰۴، ۵۰۰، آفلاین و حالت خالی؛ متن فارسیِ آدم‌وار و یک کار بعدی مشخص، نه «اوپس».", usage: `// app/not-found.tsx\nimport { ErrorPage } from "@/components/templates/error-pages"\nexport default function NotFound() {\n  return <ErrorPage kind="404" />\n}\n\n// app/error.tsx ("use client")\nexport default function Error() {\n  return <ErrorPage kind="500" />\n}`, registryDeps: ["button", "input"], promptBullets: ["Large muted error code with Persian digits; headline is a factual sentence, body two sentences with a next step; no \"Oops\" and no jokes.", "404 with a search box; 500 with a tracking code and retry; empty state with an add button."] },
  { slug: "email", name: "قالب‌های ایمیل", file: tp("email"), tags: ["ایمیل", "RTL", "جدول"], pages: 3, desc: "کد تأیید، تأیید سفارش و بازیابی رمز؛ HTML جدولی با dir=rtl روی همه‌ی عناصر و استایل درون‌خطی، برای کلاینت‌های ایمیل.", usage: `import { otpEmail, orderEmail } from "@/lib/email"\n\nawait send({ to, subject: "کد تأیید", html: otpEmail({ name: "سارا", code: "482913" }) })`, registryDeps: [], promptBullets: ["Tables and inline styles only; dir=rtl on html, body, every table and td; text-align:right.", "OTP in an LTR box with mono font and letter-spacing (allowed here because it is digits, not Persian prose).", "Tahoma/Segoe UI because web fonts do not load in email."] },
];
