import type { ThemeDoc } from "./types";

export const THEME_STORAGE_KEY = "vibefarsi-theme";

export const themes: ThemeDoc[] = [
  { slug: "graphite", name: "گرافیت", nameEn: "Graphite", desc: "سیاه خنثی، دکمه‌ی سفید، یک لهجه‌ی کهربایی. پیش‌فرض.", radius: "۱۰px", file: "registry/themes/graphite.css", swatches: ["oklch(0.115 0.002 285)", "oklch(0.14 0.002 285)", "oklch(0.975 0 0)", "oklch(0.8 0.165 65)"], promptBullets: ["Near-black background (oklch 0.115), near-white text, primary button white with black text.", "Borders white at 8% opacity; 10px radius; one amber brand accent (warm orange) for small highlights only."] },
  { slug: "turquoise", name: "فیروزه", nameEn: "Turquoise", desc: "آبی‌سبز کاشی، گوشه‌های نرم‌تر. مناسب محصول با لحن گرم.", radius: "۱۲px", file: "registry/themes/turquoise.css", swatches: ["oklch(0.15 0.03 215)", "oklch(0.18 0.03 215)", "oklch(0.83 0.13 190)", "oklch(0.88 0.1 185)"], promptBullets: ["Dark background with a blue tint (hue ~215); primary button light turquoise with dark text.", "12px radius; borders share the same tint."] },
  { slug: "saffron", name: "زعفران", nameEn: "Saffron", desc: "زمینه‌ی گرم، دکمه‌ی طلایی. مناسب فروش و رستوران.", radius: "۸px", file: "registry/themes/saffron.css", swatches: ["oklch(0.14 0.015 60)", "oklch(0.17 0.02 60)", "oklch(0.8 0.15 75)", "oklch(0.86 0.14 85)"], promptBullets: ["Warm dark background (hue ~60); primary button saffron/gold with dark brown text.", "8px radius."] },
  { slug: "pomegranate", name: "انار", nameEn: "Pomegranate", desc: "قرمز عمیق و گوشه‌های گرد. مناسب برندهای پرتحرک.", radius: "۱۶px", file: "registry/themes/pomegranate.css", swatches: ["oklch(0.14 0.02 15)", "oklch(0.17 0.025 15)", "oklch(0.7 0.18 20)", "oklch(0.8 0.12 25)"], promptBullets: ["Dark background with a red tint (hue ~15); primary button pomegranate with white text.", "16px radius, soft and round."] },
  { slug: "lapis", name: "لاجورد", nameEn: "Lapis", desc: "نیلی دقیق و گوشه‌های تیز. مناسب ابزارهای فنی.", radius: "۶px", file: "registry/themes/lapis.css", swatches: ["oklch(0.13 0.03 275)", "oklch(0.165 0.035 275)", "oklch(0.7 0.16 275)", "oklch(0.8 0.12 255)"], promptBullets: ["Dark indigo background (hue ~275); primary button blue-violet with light text.", "6px radius, precise and technical."] },
  { slug: "paper", name: "کاغذ", nameEn: "Paper", desc: "روشن و آرام، مرکب تیره. مناسب محتوا و خواندن طولانی.", radius: "۱۲px", file: "registry/themes/paper.css", swatches: ["oklch(0.985 0.004 85)", "oklch(1 0 0)", "oklch(0.2 0.01 60)", "oklch(0.68 0.17 55)"], light: true, promptBullets: ["Light theme: warm paper background, ink-dark text and primary button, color-scheme: light.", "Borders ink at 12% opacity; background patterns use dark color instead of white."] }
];
