import type { ThemeDoc } from "./types";

export const THEME_STORAGE_KEY = "vibefarsi-theme";

export const themes: ThemeDoc[] = [
  {
    slug: "graphite",
    name: "گرافیت",
    nameEn: "Graphite",
    style: "مینیمال فنی",
    styleEn: "Technical minimal",
    desc: "سیاه خنثی با خط‌های مویی، دکمه‌ی سفید و یک رنگ تأکیدی کهربایی. آرام و دقیقه و تم پیش‌فرض سایته.",
    radius: "۱۰px",
    file: "registry/themes/graphite.css",
    swatches: ["oklch(0.115 0.002 285)", "oklch(0.14 0.002 285)", "oklch(0.975 0 0)", "oklch(0.8 0.165 65)"],
    language: {
      type: "ایران‌سنس برای متن و تیتر",
      shape: "گوشه‌ی ۱۰ پیکسلی و کارت‌های گردتر",
      depth: "بدون سایه، فقط یک خط روشن بالای کارت",
      motion: "۲۰۰ میلی‌ثانیه با شتاب نرم",
      density: "معمولی",
    },
    promptBullets: [
      "Language: technical minimal. Quiet, precise, nothing decorative.",
      "Near-black background (oklch 0.115), near-white text, primary button white with black text, one amber brand accent for small highlights only.",
      "Hairline borders (white at 8%), 1px everywhere; 10px radius on controls, 22px on cards.",
      "No drop shadows. Cards get only a 1px inner top highlight. Press = scale(0.98). Motion 200ms, soft ease-out.",
    ],
  },
  {
    slug: "turquoise",
    name: "فیروزه",
    nameEn: "Turquoise",
    style: "شیشه‌ای",
    styleEn: "Glass",
    desc: "سطح‌های نیمه‌شفاف و مات روی یک پس‌زمینه‌ی نورانی فیروزه‌ای. کارت‌ها پشتشون را محو نشون میدن و لبه‌هاشون برق می‌زنه.",
    radius: "۱۴px",
    file: "registry/themes/turquoise.css",
    swatches: ["oklch(0.2 0.045 225)", "oklch(0.72 0.14 195)", "oklch(0.86 0.12 190)", "oklch(0.87 0.12 165)"],
    fonts: ["Noto Kufi Arabic"],
    language: {
      type: "تیتر با نوتو کوفی و متن با ایران‌سنس",
      shape: "گوشه‌های ۱۲ تا ۲۲ پیکسلی",
      depth: "شیشه‌ی مات با blur و سایه‌ی عمیق",
      motion: "۲۸۰ میلی‌ثانیه که آرام تموم میشه",
      density: "معمولی",
    },
    promptBullets: [
      "Language: glassmorphism. Depth comes from translucency and blur, not from solid fills.",
      "Deep teal background (hue ~225) lit by two or three large soft radial gradients (aqua, indigo, mint) behind the content.",
      "Cards and popovers are translucent (white 7%, popover 88%) with backdrop-filter: blur(20px) saturate(1.6), a 1px white-16% border and a 1px inner top highlight.",
      "Primary button light aqua with dark text and a soft aqua glow. Headings in Noto Kufi Arabic 600.",
      "Radius 12px controls, 22px cards. Motion 280ms, cubic-bezier(0.22, 1, 0.36, 1).",
    ],
  },
  {
    slug: "saffron",
    name: "زعفران",
    nameEn: "Saffron",
    style: "نئوبروتالیسم",
    styleEn: "Neo-brutalist",
    desc: "زمینه‌ی کرم و دکمه‌ی زعفرانی با خط‌های مشکی ضخیم، گوشه‌های تیز و سایه‌ی سخت. دکمه‌ها موقع کلیک واقعاً پایین می‌رن.",
    radius: "۰",
    file: "registry/themes/saffron.css",
    swatches: ["oklch(0.95 0.05 92)", "oklch(0.995 0.01 95)", "oklch(0.82 0.17 78)", "oklch(0.63 0.21 25)"],
    light: true,
    fonts: ["Lalezar"],
    language: {
      type: "تیتر با لاله‌زار و متن با ایران‌سنس",
      shape: "گوشه‌ی صفر و خط ۲ پیکسلی",
      depth: "سایه‌ی سخت و بی‌محو که به سمت چپ می‌افته",
      motion: "۹۰ میلی‌ثانیه، خطی و سریع",
      density: "معمولی",
    },
    promptBullets: [
      "Language: neo-brutalism. Loud, flat, honest; every edge is drawn in ink.",
      "Light cream background, white cards, near-black ink for text AND every border. Primary button saffron yellow with ink text; brand accent tomato red.",
      "All borders 2px solid ink. Zero radius everywhere (avatars and switches may stay round).",
      "Hard offset shadows with no blur, falling toward the inline end (left in RTL): controls -3px 3px 0 ink, cards -6px 6px 0, overlays -8px 8px 0.",
      "On press, buttons translate(-3px, 3px) and the shadow collapses to 0, so they visibly sink. Motion 90ms linear.",
      "Headings in Lalezar (400 only, never faux-bold).",
    ],
  },
  {
    slug: "pomegranate",
    name: "انار",
    nameEn: "Pomegranate",
    style: "خمیری",
    styleEn: "Soft clay",
    desc: "صورتی ملایم با دکمه‌های کپسولی و سایه‌های پف‌دار چندلایه. حرکت‌ها فنری هستن و کمی از جاشون رد میشن.",
    radius: "۲۰px",
    file: "registry/themes/pomegranate.css",
    swatches: ["oklch(0.94 0.025 15)", "oklch(0.975 0.012 15)", "oklch(0.6 0.2 18)", "oklch(0.6 0.17 340)"],
    light: true,
    fonts: ["Vazirmatn"],
    language: {
      type: "وزیرمتن، تیترها خیلی ضخیم",
      shape: "دکمه‌ی کپسولی و کارت با گوشه‌ی ۲۸ پیکسلی",
      depth: "سایه‌ی نرم بیرونی با برجستگی داخلی",
      motion: "۴۲۰ میلی‌ثانیه با فنر",
      density: "جادار",
    },
    promptBullets: [
      "Language: claymorphism. Everything looks soft, puffy and touchable.",
      "Light blush background (hue ~15), near-white cards, pomegranate primary with white text, plum brand accent. Borders almost invisible (ink 9%).",
      "Pill buttons (radius 999px), 16px fields, 28px cards.",
      "Layered shadows: a white inner top highlight, a faint inner bottom shade and a large soft colored drop shadow. Pressed buttons swap to an inset shadow and scale(0.95). Fields are slightly recessed (inset shadow).",
      "Vazirmatn for body and headings (headings 800). Spacing about 10% roomier than default. Motion 420ms spring cubic-bezier(0.34, 1.56, 0.64, 1).",
    ],
  },
  {
    slug: "lapis",
    name: "لاجورد",
    nameEn: "Lapis",
    style: "ترمینال",
    styleEn: "Terminal",
    desc: "نیلی تیره با خط‌چین، گوشه‌های تقریباً تیز و فاصله‌های فشرده. حرکت‌ها پله‌ای و فوری هستن و رنگ تأکیدش سبز فسفریه.",
    radius: "۲px",
    file: "registry/themes/lapis.css",
    swatches: ["oklch(0.14 0.03 268)", "oklch(0.165 0.035 268)", "oklch(0.72 0.16 258)", "oklch(0.84 0.19 145)"],
    fonts: ["IBM Plex Sans Arabic"],
    language: {
      type: "آی‌بی‌ام پلکس عربی برای همه‌چیز",
      shape: "گوشه‌ی ۲ پیکسلی و کارت با خط‌چین",
      depth: "بدون سایه، فقط خط",
      motion: "۱۲۰ میلی‌ثانیه و پله‌ای",
      density: "فشرده",
    },
    promptBullets: [
      "Language: terminal / developer tool. Dense, exact, information first.",
      "Dark indigo background (hue ~268), lapis-blue primary with dark text, phosphor-green brand accent and focus ring. Faint horizontal scanlines on the page background.",
      "2px radius everywhere. Cards, alerts and overlays use dashed 1px borders. Fields sit in a darker well.",
      "No shadows except a 1px primary outline around overlays. Press = translateY(1px).",
      "IBM Plex Sans Arabic for body and headings. Spacing about 10% tighter than default. Motion 120ms with steps(3), so transitions jump instead of glide.",
    ],
  },
  {
    slug: "paper",
    name: "کاغذ",
    nameEn: "Paper",
    style: "مجله‌ای",
    styleEn: "Editorial",
    desc: "کاغذ روشن و مرکب تیره با تیترهای نسخ، خط‌های نازک و فیلدهای زیرخط‌دار. هیچ سایه‌ای نداره و برای خواندن طولانی ساخته شده.",
    radius: "۲px",
    file: "registry/themes/paper.css",
    swatches: ["oklch(0.985 0.004 85)", "oklch(0.94 0.008 85)", "oklch(0.2 0.01 60)", "oklch(0.55 0.19 30)"],
    light: true,
    fonts: ["Noto Naskh Arabic"],
    language: {
      type: "تیتر با نوتو نسخ و متن با ایران‌سنس",
      shape: "گوشه‌ی ۲ پیکسلی و فیلد فقط با خط زیرین",
      depth: "بدون سایه",
      motion: "۱۶۰ میلی‌ثانیه، ساده",
      density: "کمی جادار",
    },
    promptBullets: [
      "Language: editorial / print. Typography does the work; boxes are barely there.",
      "Light theme: warm paper background, ink-dark text and primary button, vermilion brand accent, color-scheme: light. Cards share the page color and are separated by hairline rules (ink 14%).",
      "Headings in Noto Naskh Arabic 700; body stays sans. 2px radius on controls and cards.",
      "Text fields have only a bottom border (border-width 0 0 1px) on a transparent background.",
      "No drop shadows at all, except a faint one under floating overlays. Press = translateY(1px). Motion 160ms.",
    ],
  },
];
